import builtins
from ddtrace.propagation.http import HTTPPropagator
from typing import Any, Optional

generatorExit = builtins.GeneratorExit
log: Any
propagator = HTTPPropagator

def construct_url(environ: Any): ...
def get_request_headers(environ: Any): ...
def default_wsgi_span_modifier(span: Any, environ: Any) -> None: ...

class DDWSGIMiddleware:
    app: Any = ...
    tracer: Any = ...
    span_modifier: Any = ...
    def __init__(self, application: Any, tracer: Optional[Any] = ..., span_modifier: Any = ...) -> None: ...
    def __call__(self, environ: Any, start_response: Any): ...
