from ..dbapi import TracedConnection, TracedCursor
from typing import Any, Optional

def patch() -> None: ...
def unpatch() -> None: ...
def patch_conn(conn: Any): ...

class PyODBCTracedCursor(TracedCursor): ...

class PyODBCTracedConnection(TracedConnection):
    def __init__(self, conn: Any, pin: Optional[Any] = ..., cursor_cls: Optional[Any] = ...) -> None: ...
