import Any

def event_class(klass: Any): ...

class Event:
    timestamp: Any = ...
    @property
    def name(self) -> Any: ...

class TimedEvent(Event):
    duration: Any = ...

class SampleEvent(Event):
    sampling_period: Any = ...

class StackBasedEvent(SampleEvent):
    thread_id: Any = ...
    thread_name: Any = ...
    thread_native_id: Any = ...
    task_id: Any = ...
    task_name: Any = ...
    frames: Any = ...
    nframes: Any = ...
    trace_ids: Any = ...
    span_ids: Any = ...
