import Any
from ddtrace.profiling import exporter as exporter

LOG: Any

class Profiler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def start(self, stop_on_exit: bool = ..., profile_children: bool = ...) -> None: ...
    def stop(self, flush: bool = ...) -> None: ...
    @property
    def status(self) -> Any: ...
    @property
    def service(self) -> Any: ...
    @property
    def env(self) -> Any: ...
    @property
    def version(self) -> Any: ...
    @property
    def tracer(self) -> Any: ...
    @property
    def url(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
