from typing import Any

class Recorder:
    default_max_events: Any = ...
    max_events: Any = ...
    events: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def push_event(self, event: Any): ...
    def push_events(self, events: Any) -> None: ...
    def reset(self): ...
