import Any

class Recorder:
    default_max_events: Any = ...
    max_events: Any = ...
    events: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def push_event(self, event: Any): ...
    def push_events(self, events: Any) -> None: ...
    def reset(self): ...
    def __init__(self, default_max_events: Any, max_events: Any, events: Any, events_lock: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...
