import Any
from ddtrace.internal import periodic

LOG: Any

class Scheduler(periodic.PeriodicService):
    recorder: Any = ...
    exporters: Any = ...
    before_flush: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def flush(self) -> None: ...
    interval: Any = ...
    def periodic(self) -> None: ...
    def __init__(self, status: Any, service_lock: Any, worker: Any, recorder: Any, exporters: Any, before_flush: Any, interval: Any, configured_interval: Any, last_export: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...
