from ddtrace.internal import periodic
from typing import Any

LOG: Any

class Scheduler(periodic.PeriodicService):
    recorder: Any = ...
    exporters: Any = ...
    before_flush: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def start(self) -> None: ...
    def flush(self) -> None: ...
    interval: Any = ...
    def periodic(self) -> None: ...
