# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tests/contrib/protobuf/schemas/message.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 0, "", "tests/contrib/protobuf/schemas/message.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tests.contrib.protobuf.schemas import (
    other_message_pb2 as tests_dot_contrib_dot_protobuf_dot_schemas_dot_other__message__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n,tests/contrib/protobuf/schemas/message.proto\x1a\x32tests/contrib/protobuf/schemas/other_message.proto"e\n\tMyMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12$\n\rother_message\x18\x03 \x03(\x0b\x32\r.OtherMessage\x12\x17\n\x06status\x18\x04 \x01(\x0e\x32\x07.Status*<\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.contrib.protobuf.schemas.message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STATUS"]._serialized_start = 203
    _globals["_STATUS"]._serialized_end = 263
    _globals["_MYMESSAGE"]._serialized_start = 100
    _globals["_MYMESSAGE"]._serialized_end = 201
# @@protoc_insertion_point(module_scope)
