import Any
from ddtrace.internal import service
from typing import Optional

class PeriodicService(service.Service):
    @property
    def interval(self): ...
    @interval.setter
    def interval(self, value: Any) -> None: ...
    def join(self, timeout: Optional[Any] = ...) -> None: ...
    def stop(self) -> None: ...
    @staticmethod
    def on_shutdown() -> None: ...
    @staticmethod
    def periodic() -> None: ...
