import Any
import abc
import typing

class Service(metaclass=abc.ABCMeta):
    status: Any = ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def start(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def stop(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def join(self, timeout: typing.Optional[float]=...) -> None: ...
    def __init__(self, status: Any, service_lock: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...
