# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.subprocess.patch import patch


try:
    from ddtrace.contrib.subprocess.patch import unpatch
except ImportError:
    unpatch = None
from tests.contrib.patch import PatchTestCase


class TestSubprocessPatch(PatchTestCase.Base):
    __integration_name__ = "subprocess"
    __module_name__ = "subprocess"
    __patch_func__ = patch
    __unpatch_func__ = unpatch

    def assert_module_patched(self, subprocess):
        import os

        self.assert_wrapped(subprocess.Popen.__init__)
        self.assert_wrapped(subprocess.Popen.wait)
        self.assert_wrapped(os.system)
        self.assert_wrapped(os.fork)

    def assert_not_module_patched(self, subprocess):
        import os

        self.assert_not_wrapped(subprocess.Popen.__init__)
        self.assert_not_wrapped(subprocess.Popen.wait)
        self.assert_not_wrapped(os.system)
        self.assert_not_wrapped(os.fork)

    def assert_not_module_double_patched(self, subprocess):
        import os

        self.assert_not_double_wrapped(subprocess.Popen.__init__)
        self.assert_not_double_wrapped(subprocess.Popen.wait)
        self.assert_not_double_wrapped(os.system)
        self.assert_not_double_wrapped(os.fork)
