from typing import Any

log: Any

def get_resource(scope: Any): ...
def span_modifier(span: Any, scope: Any) -> None: ...
def traced_init(wrapped: Any, instance: Any, args: Any, kwargs: Any) -> None: ...
def patch() -> None: ...
def unpatch() -> None: ...
