from typing import Any, Optional

class TracePlugin:
    name: str = ...
    api: int = ...
    service: Any = ...
    tracer: Any = ...
    def __init__(self, service: str = ..., tracer: Optional[Any] = ..., distributed_tracing: Optional[Any] = ...) -> None: ...
    @property
    def distributed_tracing(self): ...
    @distributed_tracing.setter
    def distributed_tracing(self, distributed_tracing: Any) -> None: ...
    def apply(self, callback: Any, route: Any): ...
