from ...contrib.dbapi import FetchTracedCursor, TracedConnection, TracedCursor
from typing import Any, Optional

def patch() -> None: ...
def unpatch() -> None: ...
def traced_connect(func: Any, _: Any, args: Any, kwargs: Any): ...
def patch_conn(conn: Any): ...

class TracedSQLiteCursor(TracedCursor):
    def executemany(self, *args: Any, **kwargs: Any): ...
    def execute(self, *args: Any, **kwargs: Any): ...

class TracedSQLiteFetchCursor(TracedSQLiteCursor, FetchTracedCursor): ...

class TracedSQLite(TracedConnection):
    def __init__(self, conn: Any, pin: Optional[Any] = ..., cursor_cls: Optional[Any] = ...) -> None: ...
    def execute(self, *args: Any, **kwargs: Any): ...
