version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "1.86"
  commands:
    - cargo install --force --root /home/docs/.asdf --git https://github.com/DataDog/libdatadog --bin dedup_headers tools
    - git fetch --unshallow || true
    - pip install uv==0.12.5
    - READTHEDOCS=1 uv run --no-project --python 3.10 --no-python-downloads --with-editable . --with-requirements .uv/build-docs--build-docs-py310.txt scripts/docs/build.sh
    - mv docs/_build $READTHEDOCS_OUTPUT
