FROM kennethreitz/httpbin:latest

RUN apt-get update -y && apt-get install -y --no-install-recommends git build-essential
RUN pip3 install setuptools cython
RUN pip3 install git+https://github.com/DataDog/dd-trace-py@nicolas.vivet/appsec-demo

CMD ["ddtrace-run", "gunicorn", "-b", "0.0.0.0:80", "-k", "gthread", "--access-logfile", "-", "httpbin:app"]
