FROM kennethreitz/httpbin:latest

RUN apt-get update -y && apt-get install -y --no-install-recommends git build-essential python3-setuptools
# cython from bionic is not recent enough
RUN pip3 install cython

ADD . /src
RUN pip3 install -e /src

CMD ["ddtrace-run", "gunicorn", "-b", "0.0.0.0:80", "httpbin:app", "-k", "gthread"]
