# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traces.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='traces.proto',
  package='encoding',
  syntax='proto3',
  serialized_pb=_b('\n\x0ctraces.proto\x12\x08\x65ncoding\"\xde\x02\n\x04Span\x12\x10\n\x08trace_id\x18\x01 \x01(\x04\x12\x11\n\tparent_id\x18\x02 \x01(\x04\x12\x0f\n\x07span_id\x18\x03 \x01(\x04\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x10\n\x08resource\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\r\n\x05\x65rror\x18\x07 \x01(\x05\x12\r\n\x05start\x18\x08 \x01(\x03\x12\x10\n\x08\x64uration\x18\t \x01(\x03\x12\x0c\n\x04type\x18\n \x01(\t\x12&\n\x04meta\x18\x0b \x03(\x0b\x32\x18.encoding.Span.MetaEntry\x12,\n\x07metrics\x18\x0c \x03(\x0b\x32\x1b.encoding.Span.MetricsEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"&\n\x06Traces\x12\x1c\n\x04span\x18\x01 \x03(\x0b\x32\x0e.encoding.Spanb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPAN_METAENTRY = _descriptor.Descriptor(
  name='MetaEntry',
  full_name='encoding.Span.MetaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='encoding.Span.MetaEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='encoding.Span.MetaEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=329,
)

_SPAN_METRICSENTRY = _descriptor.Descriptor(
  name='MetricsEntry',
  full_name='encoding.Span.MetricsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='encoding.Span.MetricsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='encoding.Span.MetricsEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=377,
)

_SPAN = _descriptor.Descriptor(
  name='Span',
  full_name='encoding.Span',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='encoding.Span.trace_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='encoding.Span.parent_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='span_id', full_name='encoding.Span.span_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service', full_name='encoding.Span.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='encoding.Span.resource', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='encoding.Span.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='encoding.Span.error', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='encoding.Span.start', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='encoding.Span.duration', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='encoding.Span.type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='encoding.Span.meta', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='encoding.Span.metrics', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SPAN_METAENTRY, _SPAN_METRICSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=377,
)


_TRACES = _descriptor.Descriptor(
  name='Traces',
  full_name='encoding.Traces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='span', full_name='encoding.Traces.span', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=417,
)

_SPAN_METAENTRY.containing_type = _SPAN
_SPAN_METRICSENTRY.containing_type = _SPAN
_SPAN.fields_by_name['meta'].message_type = _SPAN_METAENTRY
_SPAN.fields_by_name['metrics'].message_type = _SPAN_METRICSENTRY
_TRACES.fields_by_name['span'].message_type = _SPAN
DESCRIPTOR.message_types_by_name['Span'] = _SPAN
DESCRIPTOR.message_types_by_name['Traces'] = _TRACES

Span = _reflection.GeneratedProtocolMessageType('Span', (_message.Message,), dict(

  MetaEntry = _reflection.GeneratedProtocolMessageType('MetaEntry', (_message.Message,), dict(
    DESCRIPTOR = _SPAN_METAENTRY,
    __module__ = 'traces_pb2'
    # @@protoc_insertion_point(class_scope:encoding.Span.MetaEntry)
    ))
  ,

  MetricsEntry = _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SPAN_METRICSENTRY,
    __module__ = 'traces_pb2'
    # @@protoc_insertion_point(class_scope:encoding.Span.MetricsEntry)
    ))
  ,
  DESCRIPTOR = _SPAN,
  __module__ = 'traces_pb2'
  # @@protoc_insertion_point(class_scope:encoding.Span)
  ))
_sym_db.RegisterMessage(Span)
_sym_db.RegisterMessage(Span.MetaEntry)
_sym_db.RegisterMessage(Span.MetricsEntry)

Traces = _reflection.GeneratedProtocolMessageType('Traces', (_message.Message,), dict(
  DESCRIPTOR = _TRACES,
  __module__ = 'traces_pb2'
  # @@protoc_insertion_point(class_scope:encoding.Traces)
  ))
_sym_db.RegisterMessage(Traces)


_SPAN_METAENTRY.has_options = True
_SPAN_METAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SPAN_METRICSENTRY.has_options = True
_SPAN_METRICSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
