"""Shared pytest-xdist command-line helpers for Test Optimization plugins."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import tempfile
import typing as t

from ddtrace.internal.logger import get_logger
from ddtrace.testing.internal.constants import DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA
from ddtrace.testing.internal.constants import DD_TEST_OPTIMIZATION_MANIFEST_FILE
from ddtrace.testing.internal.git import GitTag
from ddtrace.testing.internal.manifest import write_manifest_cache
from ddtrace.testing.internal.offline_mode import get_offline_mode
from ddtrace.testing.internal.offline_mode import reset_offline_mode


if t.TYPE_CHECKING:
    from ddtrace.testing.internal.session_manager import SessionManager


log = get_logger(__name__)

XDIST_UNSET = "UNSET"
XDIST_AUTO = "auto"
XDIST_LOGICAL = "logical"

# AIDEV-NOTE: The controller-generated manifest cache lives in a private temp directory instead of the workspace: the
# workspace path is derived differently by different components (git root vs. CI provider env vars), and two concurrent
# pytest runs of the same repo would otherwise clobber each other's cache.  The controller pid is embedded in the
# directory name so descendant processes can tell whether an inherited manifest env var was meant for them.
XDIST_MANIFEST_DIR_PREFIX = "dd_xdist_manifest_"


def is_xdist_worker_process() -> bool:
    """Return whether this process is a pytest-xdist worker (the env var is set before plugins load)."""
    return bool(os.environ.get("PYTEST_XDIST_WORKER"))


class XdistManifest(t.NamedTuple):
    """Bookkeeping for the manifest cache an xdist controller generated for its workers."""

    directory: Path
    path: Path
    git_metadata_exported: bool


def generate_xdist_manifest(session_manager: SessionManager) -> t.Optional[XdistManifest]:
    """Publish the controller's backend data as a manifest cache for the xdist workers it is about to spawn.

    Without this, every worker would query settings, known tests, test management and skippable tests again.  Workers
    are spawned after the plugin's early hooks run, so exporting the manifest env var once the cache is fully written
    is all they need to inherit manifest mode -- no waiting or retrying on the worker side.

    Returns the bookkeeping needed by ``cleanup_xdist_manifest``, or None when no manifest was generated.
    """
    if get_offline_mode().manifest_enabled:
        # A user-provided manifest (Bazel) is already in effect: workers inherit it as-is.
        return None

    manifest_dir = Path(tempfile.mkdtemp(prefix=f"{XDIST_MANIFEST_DIR_PREFIX}{os.getpid()}_"))
    try:
        manifest_path = write_manifest_cache(
            manifest_dir,
            session_manager.settings,
            session_manager.known_tests,
            session_manager.test_properties,
            session_manager.skippable_items,
            session_manager.itr_correlation_id,
        )
    except (OSError, TypeError) as e:
        log.debug("Could not write xdist manifest cache %s: %s", manifest_dir, e)
        shutil.rmtree(manifest_dir, ignore_errors=True)
        return None

    os.environ[DD_TEST_OPTIMIZATION_MANIFEST_FILE] = str(manifest_path)
    git_metadata_exported = _export_git_metadata_for_workers(session_manager.env_tags)
    log.debug(
        "Test Optimization xdist controller generated manifest cache for workers: path=%s git_metadata_exported=%s",
        manifest_path,
        git_metadata_exported,
    )
    return XdistManifest(directory=manifest_dir, path=manifest_path, git_metadata_exported=git_metadata_exported)


def cleanup_xdist_manifest(manifest: XdistManifest, env_tags: t.Mapping[str, t.Optional[str]]) -> None:
    """Remove the generated manifest cache and the env vars exported for the workers."""
    if os.environ.get(DD_TEST_OPTIMIZATION_MANIFEST_FILE) == str(manifest.path):
        os.environ.pop(DD_TEST_OPTIMIZATION_MANIFEST_FILE, None)
    shutil.rmtree(manifest.directory, ignore_errors=True)
    if manifest.git_metadata_exported:
        _cleanup_exported_git_metadata(env_tags)


def discard_foreign_generated_manifest_env() -> None:
    """Drop an inherited generated-manifest env var that belongs to another pytest session.

    Workers are direct children of the controller that generated the manifest, so they keep it.  Any other descendant
    (typically a nested pytest run started from inside a worker) must not read the outer session's cached backend data,
    so the env var is removed before the plugin resolves offline mode.  User-provided manifests (Bazel) are untouched.
    """
    manifest_env = os.environ.get(DD_TEST_OPTIMIZATION_MANIFEST_FILE)
    if not manifest_env:
        return
    owner_pid = _generated_manifest_owner_pid(manifest_env)
    if owner_pid is None or owner_pid in (os.getpid(), os.getppid()):
        return
    log.debug(
        "Ignoring Test Optimization manifest generated by an unrelated session: path=%s owner_pid=%s ppid=%s",
        manifest_env,
        owner_pid,
        os.getppid(),
    )
    os.environ.pop(DD_TEST_OPTIMIZATION_MANIFEST_FILE, None)
    reset_offline_mode()


def warn_if_worker_manifest_unusable() -> None:
    """Log when a worker inherited a manifest from its controller but cannot use it.

    Workers are spawned in ``DSession.pytest_sessionstart``, long after the controller wrote the cache and exported
    ``DD_TEST_OPTIMIZATION_MANIFEST_FILE``, so this should not happen.  If it does (cache removed or truncated by
    something else), the worker silently falls back to querying the backend, which is safe but defeats the whole point
    of the manifest -- so make it visible instead of hiding it behind a debug log.
    """
    if not is_xdist_worker_process():
        return
    manifest_env = os.environ.get(DD_TEST_OPTIMIZATION_MANIFEST_FILE)
    if not manifest_env or _generated_manifest_owner_pid(manifest_env) is None:
        return
    if get_offline_mode().manifest_enabled:
        return
    log.warning(
        "Test Optimization xdist worker %s could not read the manifest generated by its controller (%s) and will "
        "query the backend instead",
        os.environ.get("PYTEST_XDIST_WORKER"),
        manifest_env,
    )


def _generated_manifest_owner_pid(manifest_path: str) -> t.Optional[int]:
    """Return the pid of the controller that generated ``manifest_path``, or None if we did not generate it."""
    dir_name = Path(manifest_path).parent.name
    if not dir_name.startswith(XDIST_MANIFEST_DIR_PREFIX):
        return None
    pid_part = dir_name[len(XDIST_MANIFEST_DIR_PREFIX) :].split("_", 1)[0]
    try:
        return int(pid_part)
    except ValueError:
        return None


def _export_git_metadata_for_workers(env_tags: t.Mapping[str, t.Optional[str]]) -> bool:
    """Export controller-only git metadata through env so xdist workers can read it at startup."""
    merge_base = env_tags.get(GitTag.PULL_REQUEST_BASE_BRANCH_SHA)
    if merge_base and DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA not in os.environ:
        os.environ[DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA] = merge_base
        return True
    return False


def _cleanup_exported_git_metadata(env_tags: t.Mapping[str, t.Optional[str]]) -> None:
    merge_base = env_tags.get(GitTag.PULL_REQUEST_BASE_BRANCH_SHA)
    if merge_base and os.environ.get(DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA) == merge_base:
        os.environ.pop(DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA, None)


def parse_worker_value(val: str) -> t.Union[int, str]:
    """Parse a pytest-xdist worker-count value."""
    if val in (XDIST_AUTO, XDIST_LOGICAL):
        return val
    try:
        return int(val)
    except ValueError:
        return XDIST_UNSET


def parse_xdist_args_from_cmd(args: list[str]) -> tuple[t.Union[int, str], str]:
    """Parse pytest-xdist worker-count and distribution mode arguments."""
    num_workers: t.Union[int, str] = XDIST_UNSET
    dist_mode = XDIST_UNSET

    def set_workers_and_dist(val: str) -> None:
        nonlocal num_workers, dist_mode
        num_workers = parse_worker_value(val)
        if (
            num_workers
            and (isinstance(num_workers, int) or num_workers in (XDIST_AUTO, XDIST_LOGICAL))
            and dist_mode == XDIST_UNSET
        ):
            dist_mode = "load"

    i = 0
    while i < len(args):
        arg = args[i]

        if arg == "-n" and i + 1 < len(args):
            set_workers_and_dist(args[i + 1])
            i += 1
        elif arg.startswith("-n") and len(arg) > 2:
            set_workers_and_dist(arg[2:])
        elif arg == "--numprocesses" and i + 1 < len(args):
            set_workers_and_dist(args[i + 1])
            i += 1
        elif arg.startswith("--numprocesses="):
            set_workers_and_dist(arg.split("=", 1)[1])
        elif arg == "--dist" and i + 1 < len(args):
            dist_mode = args[i + 1]
            i += 1
        elif arg.startswith("--dist="):
            dist_mode = arg.split("=", 1)[1]

        i += 1

    return num_workers, dist_mode


def is_xdist_enabled_from_args(args: list[str]) -> bool:
    """Return whether command-line args or the live environment indicate xdist is active."""
    num_workers, _ = parse_xdist_args_from_cmd(args)
    return num_workers not in (XDIST_UNSET, 0, None) or bool(os.environ.get("PYTEST_XDIST_WORKER"))
