from typing import Any

CTX_KEY: str
PRODUCER_ROOT_SPAN: str
WORKER_ROOT_SPAN: str
TASK_TAG_KEY: str
TASK_APPLY: str
TASK_APPLY_ASYNC: str
TASK_RUN: str
TASK_RETRY_REASON_KEY: str
APP: str
PRODUCER_SERVICE: Any
WORKER_SERVICE: Any
