from ...propagation.http import HTTPPropagator
from typing import Any

log: Any
propagator = HTTPPropagator

def trace_prerun(*args: Any, **kwargs: Any) -> None: ...
def trace_postrun(*args: Any, **kwargs: Any) -> None: ...
def trace_before_publish(*args: Any, **kwargs: Any) -> None: ...
def trace_after_publish(*args: Any, **kwargs: Any) -> None: ...
def trace_failure(*args: Any, **kwargs: Any) -> None: ...
def trace_retry(*args: Any, **kwargs: Any) -> None: ...
