from ddtrace.span import Span
from typing import Any, Dict

TAG_KEYS: Any

def set_tags_from_context(span: Span, context: Dict[str, Any]) -> None: ...
def attach_span(task: Any, task_id: Any, span: Any, is_publish: bool = ...) -> None: ...
def detach_span(task: Any, task_id: Any, is_publish: bool = ...) -> None: ...
def retrieve_span(task: Any, task_id: Any, is_publish: bool = ...): ...
def retrieve_task_id(context: Any): ...
