from typing import Any

log: Any
FLASK_ENDPOINT: str
FLASK_VIEW_ARGS: str
FLASK_URL_RULE: str
FLASK_VERSION: str
flask_version_str: Any
flask_version: Any

def patch() -> None: ...
def unpatch() -> None: ...
def traced_wsgi_app(pin: Any, wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_blueprint_register(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_blueprint_add_url_rule(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_add_url_rule(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_endpoint(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_flask_hook(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_render_template(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_render_template_string(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_render(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced__register_error_handler(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_register_error_handler(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def request_tracer(name: Any): ...
def traced_signal_receivers_for(signal: Any): ...
def traced_jsonify(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
