import cherrypy
from typing import Any, Optional

log: Any
SPAN_NAME: str

class TraceTool(cherrypy.Tool):
    app: Any = ...
    def __init__(self, app: Any, tracer: Any, service: Any, use_distributed_tracing: Optional[Any] = ...) -> None: ...
    @property
    def use_distributed_tracing(self): ...
    @use_distributed_tracing.setter
    def use_distributed_tracing(self, use_distributed_tracing: Any) -> None: ...
    @property
    def service(self): ...
    @service.setter
    def service(self, service: Any) -> None: ...

class TraceMiddleware:
    app: Any = ...
    def __init__(self, app: Any, tracer: Any, service: str = ..., distributed_tracing: Optional[Any] = ...) -> None: ...
