import Any
from ddtrace.profiling.exporter import pprof

class PprofFileExporter(pprof.PprofExporter):
    prefix: Any = ...
    def export(self, events: Any, start_time_ns: Any, end_time_ns: Any) -> None: ...
    def __init__(self, prefix: Any, increment: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...
