import Any
import tenacity
from ddtrace.profiling import exporter
from ddtrace.profiling.exporter import pprof

HOSTNAME: Any
PYTHON_IMPLEMENTATION: Any
PYTHON_VERSION: Any

class UploadFailed(tenacity.RetryError, exporter.ExportError): ...

class PprofHTTPExporter(pprof.PprofExporter):
    endpoint: Any = ...
    api_key: Any = ...
    timeout: Any = ...
    service: Any = ...
    env: Any = ...
    version: Any = ...
    tags: Any = ...
    max_retry_delay: Any = ...
    endpoint_path: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def export(self, events: Any, start_time_ns: Any, end_time_ns: Any) -> None: ...
    def __init__(self, endpoint: Any, api_key: Any, timeout: Any, service: Any, env: Any, version: Any, tags: Any, max_retry_delay: Any, container_info: Any, retry_upload: Any, endpoint_path: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...
