import tenacity
from ddtrace.profiling import exporter
from ddtrace.profiling.exporter import pprof
from typing import Any

HOSTNAME: Any
PYTHON_IMPLEMENTATION: Any
PYTHON_VERSION: Any

class UploadFailed(tenacity.RetryError, exporter.ExportError): ...

class PprofHTTPExporter(pprof.PprofExporter):
    endpoint: Any = ...
    api_key: Any = ...
    timeout: Any = ...
    service: Any = ...
    env: Any = ...
    version: Any = ...
    tags: Any = ...
    max_retry_delay: Any = ...
    endpoint_path: Any = ...
    def __attrs_post_init__(self) -> None: ...
    def export(self, events: Any, start_time_ns: Any, end_time_ns: Any) -> None: ...
