import pytest

from ddtrace.ext import aws
from ddtrace.ext import ci
from ddtrace.ext import git


def test_flatten_dict():
    """Ensure that flattening of a nested dict results in a normalized, 1-level dict"""
    d = dict(A=1, B=2, C=dict(A=3, B=4, C=dict(A=5, B=6)))
    e = dict(A=1, B=2, C_A=3, C_B=4, C_C_A=5, C_C_B=6)
    assert aws._flatten_dict(d, sep="_") == e


AZURE = [
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI": "",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI": "sample2",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample2",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEBRANCH": "",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCECOMMITID": "",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar~",
            "BUILD_SOURCEVERSION": "commit",
            "HOME": "/not-my-home",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
            "USERPROFILE": "/not-my-home",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar~",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "/foo/~/bar",
            "BUILD_SOURCEVERSION": "commit",
            "HOME": "/not-my-home",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
            "USERPROFILE": "/not-my-home",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/~/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "~/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "HOME": "/not-my-home",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
            "USERPROFILE": "/not-my-home",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/not-my-home/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "~foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "HOME": "/not-my-home",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
            "USERPROFILE": "/not-my-home",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "~foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "~",
            "BUILD_SOURCEVERSION": "commit",
            "HOME": "/not-my-home",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
            "USERPROFILE": "/not-my-home",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/not-my-home",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "refs/heads/master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "master",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "refs/heads/feature/one",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "feature/one",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/tags/0.1.0",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
            "git.tag": "0.1.0",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "refs/heads/tags/0.1.0",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.commit.sha": "commit",
            "git.commit_sha": "commit",
            "git.repository_url": "sample",
            "git.tag": "0.1.0",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "origin/master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEBRANCH": "origin/pr",
            "SYSTEM_PULLREQUEST_SOURCECOMMITID": "commitPR",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "pr",
            "git.commit.sha": "commitPR",
            "git.commit_sha": "commitPR",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "refs/heads/master",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEBRANCH": "refs/heads/pr",
            "SYSTEM_PULLREQUEST_SOURCECOMMITID": "commitPR",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "pr",
            "git.commit.sha": "commitPR",
            "git.commit_sha": "commitPR",
            "git.repository_url": "sample",
        },
    ],
    [
        {
            "BUILD_BUILDID": "azure-pipelines-build-id",
            "BUILD_DEFINITIONNAME": "azure-pipelines-name",
            "BUILD_REPOSITORY_URI": "sample",
            "BUILD_SOURCEBRANCH": "refs/heads/feature/one",
            "BUILD_SOURCESDIRECTORY": "/foo/bar",
            "BUILD_SOURCEVERSION": "commit",
            "SYSTEM_JOBID": "azure-pipelines-job-id",
            "SYSTEM_PULLREQUEST_SOURCEBRANCH": "refs/heads/pr",
            "SYSTEM_PULLREQUEST_SOURCECOMMITID": "commitPR",
            "SYSTEM_TASKINSTANCEID": "azure-pipelines-task-id",
            "SYSTEM_TEAMFOUNDATIONSERVERURI": "azure-pipelines-server-uri/",
            "SYSTEM_TEAMPROJECT": "azure-pipelines-project",
            "TF_BUILD": "True",
        },
        {
            "ci.job.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&view=logs&j=azure-pipelines-job-id&t=azure-pipelines-task-id",
            "ci.pipeline.id": "azure-pipelines-build-id",
            "ci.pipeline.name": "azure-pipelines-name",
            "ci.pipeline.number": "azure-pipelines-build-id",
            "ci.pipeline.url": "azure-pipelines-server-uri/azure-pipelines-project/_build/results?buildId=azure-pipelines-build-id&_a=summary",
            "ci.provider.name": "azurepipelines",
            "ci.workspace_path": "/foo/bar",
            "git.branch": "pr",
            "git.commit.sha": "commitPR",
            "git.commit_sha": "commitPR",
            "git.repository_url": "sample",
        },
    ],
]


def _updateenv(monkeypatch, env):
    for k, v in env.items():
        monkeypatch.setenv(k, v)


@pytest.mark.parametrize("environment,tags", AZURE)
def test_ci_providers(monkeypatch, environment, tags):
    _updateenv(monkeypatch, environment)
    assert tags == ci.tags(), environment
