from typing import Any

log: Any

class Config:
    http: Any = ...
    analytics_enabled: Any = ...
    tags: Any = ...
    env: Any = ...
    service: Any = ...
    version: Any = ...
    service_mapping: Any = ...
    logs_injection: Any = ...
    report_hostname: Any = ...
    health_metrics_enabled: Any = ...
    def __init__(self) -> None: ...
    def __getattr__(self, name: Any): ...
    def get_from(self, obj: Any): ...
    def trace_headers(self, whitelist: Any): ...
    def header_is_traced(self, header_name: Any): ...
