from typing import Any, List, Tuple

log: Any

def get_error_ranges(error_range_str: builtins.str) -> List[Tuple[int, int]]: ...

class Config:
    class HTTPServerConfig:
        @property
        def error_statuses(self) -> str: ...
        @property
        def error_ranges(self) -> List[Tuple[int, int]]: ...
        @error_statuses.setter
        def error_statuses(self, value: str) -> None: ...
        def is_error_code(self, status_code: int) -> bool: ...
    http: Any = ...
    analytics_enabled: Any = ...
    tags: Any = ...
    env: Any = ...
    service: Any = ...
    version: Any = ...
    http_server: Any = ...
    service_mapping: Any = ...
    logs_injection: Any = ...
    report_hostname: Any = ...
    health_metrics_enabled: Any = ...
    def __init__(self) -> None: ...
    def __getattr__(self, name: Any): ...
    def get_from(self, obj: Any): ...
    def trace_headers(self, whitelist: Any): ...
    def header_is_traced(self, header_name: Any): ...
