import Any

log: Any

class HttpConfig:
    trace_query_string: Any = ...
    def __init__(self) -> None: ...
    @property
    def is_header_tracing_configured(self) -> Any: ...
    def trace_headers(self, whitelist: Any): ...
    def header_is_traced(self, header_name: Any): ...
