from typing import Any, List, Optional, Union

log: Any

class HttpConfig:
    trace_query_string: Any = ...
    def __init__(self) -> None: ...
    @property
    def is_header_tracing_configured(self) -> bool: ...
    def trace_headers(self, whitelist: Union[List[str], str]) -> Optional[HttpConfig]: ...
    def header_is_traced(self, header_name: str) -> bool: ...
