import Any
from ..utils.attrdict import AttrDict

class IntegrationConfig(AttrDict):
    def __init__(self, global_config: Any, name: Any, *args: Any, **kwargs: Any) -> None: ...
    @property
    def trace_query_string(self) -> Any: ...
    @property
    def is_header_tracing_configured(self) -> bool: ...
    def header_is_traced(self, header_name: Any): ...
    def get_analytics_sample_rate(self, use_global_config: bool = ...): ...
