import Any
from ..utils.attrdict import AttrDict
from typing import Optional

class IntegrationConfig(AttrDict):
    def __init__(self, global_config: Any, name: Any, *args: Any, **kwargs: Any) -> None: ...
    def __deepcopy__(self, memodict: Optional[Any] = ...): ...
    def copy(self): ...
    @property
    def trace_query_string(self) -> Any: ...
    def header_is_traced(self, header_name: Any): ...
    def get_analytics_sample_rate(self, use_global_config: bool = ...): ...
