from typing import Any

PATCH_ALL_HELP_MSG: str
log: Any

def is_enabled(config: Any): ...
def pytest_addoption(parser: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
def pytest_sessionfinish(session: Any, exitstatus: Any) -> None: ...
def ddspan(request: Any): ...
def patch_all(request: Any) -> None: ...
def pytest_runtest_protocol(item: Any, nextitem: Any) -> None: ...
def pytest_runtest_makereport(item: Any, call: Any) -> None: ...
