from typing import Any

def execute(func: Any, handler: Any, args: Any, kwargs: Any): ...
def on_finish(func: Any, handler: Any, args: Any, kwargs: Any): ...
def log_exception(func: Any, handler: Any, args: Any, kwargs: Any): ...
