from typing import Any

log: Any
SANIC_PRE_21: Any

def update_span(span: Any, response: Any) -> None: ...
async def patch_request_respond(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
async def patch_run_request_middleware(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def patch() -> None: ...
def unpatch() -> None: ...
async def patch_handle_request(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
