from typing import Any

GRPC_PIN_MODULE_SERVER: Any
GRPC_PIN_MODULE_CLIENT: Any
GRPC_METHOD_PATH_KEY: str
GRPC_METHOD_PACKAGE_KEY: str
GRPC_METHOD_SERVICE_KEY: str
GRPC_METHOD_NAME_KEY: str
GRPC_METHOD_KIND_KEY: str
GRPC_STATUS_CODE_KEY: str
GRPC_REQUEST_METADATA_PREFIX_KEY: str
GRPC_RESPONSE_METADATA_PREFIX_KEY: str
GRPC_HOST_KEY: str
GRPC_PORT_KEY: str
GRPC_SPAN_KIND_KEY: str
GRPC_SPAN_KIND_VALUE_CLIENT: str
GRPC_SPAN_KIND_VALUE_SERVER: str
GRPC_METHOD_KIND_UNARY: str
GRPC_METHOD_KIND_CLIENT_STREAMING: str
GRPC_METHOD_KIND_SERVER_STREAMING: str
GRPC_METHOD_KIND_BIDI_STREAMING: str
GRPC_SERVICE_SERVER: str
GRPC_SERVICE_CLIENT: str
