from typing import Any

log: Any

def parse_method_path(method_path: Any): ...
def set_grpc_method_meta(span: Any, method: Any, method_kind: Any) -> None: ...
def set_grpc_client_meta(span: Any, host: Any, port: Any) -> None: ...
