from typing import Any

log: Any

def copy_span_start(instance: Any, span: Any, conf: Any, *args: Any, **kwargs: Any) -> None: ...
def execute_span_start(instance: Any, span: Any, conf: Any, *args: Any, **kwargs: Any) -> None: ...
def execute_span_end(instance: Any, result: Any, span: Any, conf: Any, *args: Any, **kwargs: Any) -> None: ...
def fetch_span_end(instance: Any, result: Any, span: Any, conf: Any, *args: Any, **kwargs: Any) -> None: ...
def cursor_span_end(instance: Any, cursor: Any, _: Any, conf: Any, *args: Any, **kwargs: Any) -> None: ...
def patch() -> None: ...
def unpatch() -> None: ...
