# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.logbook import get_version
from ddtrace.contrib.logbook.patch import patch


try:
    from ddtrace.contrib.logbook.patch import unpatch
except ImportError:
    unpatch = None
from tests.contrib.patch import PatchTestCase


class TestLogbookPatch(PatchTestCase.Base):
    __integration_name__ = "logbook"
    __module_name__ = "logbook"
    __patch_func__ = patch
    __unpatch_func__ = unpatch
    __get_version__ = get_version

    def assert_module_patched(self, logbook):
        self.assert_wrapped(logbook.base.RecordDispatcher.process_record)

    def assert_not_module_patched(self, logbook):
        self.assert_not_wrapped(logbook.base.RecordDispatcher.process_record)

    def assert_not_module_double_patched(self, logbook):
        self.assert_not_double_wrapped(logbook.base.RecordDispatcher.process_record)
