# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.internal.logging.patch import get_version
from ddtrace.contrib.internal.logging.patch import patch


try:
    from ddtrace.contrib.internal.logging.patch import unpatch
except ImportError:
    unpatch = None  # type: ignore[assignment]
from tests.contrib.patch import PatchTestCase


class TestLoggingPatch(PatchTestCase.Base):
    __integration_name__ = "logging"  # type: ignore[assignment]
    __module_name__ = "logging"  # type: ignore[assignment]
    __patch_func__ = patch  # type: ignore[assignment]
    __unpatch_func__ = unpatch  # type: ignore[assignment]
    __get_version__ = get_version  # type: ignore[assignment]

    def assert_module_patched(self, logging):
        pass

    def assert_not_module_patched(self, logging):
        pass

    def assert_not_module_double_patched(self, logging):
        pass

    def test_and_emit_get_version(self):
        version = get_version()
        assert type(version) == str
        assert version == ""
