from typing import Any, Optional

def set_call_context(task: Any, ctx: Any) -> None: ...
def ensure_future(coro_or_future: Any, *, loop: Optional[Any] = ..., tracer: Optional[Any] = ...): ...
def run_in_executor(loop: Any, executor: Any, func: Any, *args: Any, tracer: Optional[Any] = ...): ...
def create_task(*args: Any, **kwargs: Any): ...
