from typing import Any

DD_PATCH: str

def patch() -> None: ...
def traced_init(wrapped: Any, instance: Any, args: Any, kwargs: Any) -> None: ...
def insert_tween_if_needed(settings: Any) -> None: ...
