from typing import Any

log: Any
DD_TWEEN_NAME: str
DD_SPAN: str

def trace_pyramid(config: Any) -> None: ...
def includeme(config: Any) -> None: ...
def trace_render(func: Any, instance: Any, args: Any, kwargs: Any): ...
def trace_tween_factory(handler: Any, registry: Any): ...
