import Any

RECORD_ATTR_TRACE_ID: str
RECORD_ATTR_SPAN_ID: str
RECORD_ATTR_ENV: str
RECORD_ATTR_VERSION: str
RECORD_ATTR_SERVICE: str
RECORD_ATTR_VALUE_ZERO: str
RECORD_ATTR_VALUE_EMPTY: str

class DDLogRecord:
    trace_id: Any = ...
    span_id: Any = ...
    service: Any = ...
    version: Any = ...
    env: Any = ...
    def __init__(self, trace_id: Any, span_id: Any, service: Any, version: Any, env: Any) -> None: ...
    def __lt__(self, other: _AT`-1) -> Any: ...
    def __le__(self, other: _AT`-1) -> Any: ...
    def __gt__(self, other: _AT`-1) -> Any: ...
    def __ge__(self, other: _AT`-1) -> Any: ...

def patch() -> None: ...
def unpatch() -> None: ...
