# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x1c\n\nApiRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\"!\n\x05Items\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.api.Item\"(\n\nMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"e\n\x07MapTest\x12*\n\x07mapTest\x18\x01 \x03(\x0b\x32\x19.api.MapTest.MapTestEntry\x1a.\n\x0cMapTestEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\rMsgMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.api.Item\"\x7f\n\nMsgMapTest\x12\x33\n\nmsgMapTest\x18\x01 \x03(\x0b\x32\x1f.api.MsgMapTest.MsgMapTestEntry\x1a<\n\x0fMsgMapTestEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.api.Item:\x02\x38\x01\" \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05Hello\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe7\x01\n\x03\x41pi\x12+\n\x08sayHello\x12\x11.api.HelloRequest\x1a\n.api.Hello\"\x00\x12\'\n\x06getAll\x12\x0f.api.ApiRequest\x1a\n.api.Items\"\x00\x12+\n\tgetStream\x12\x0f.api.ApiRequest\x1a\t.api.Item\"\x00\x30\x01\x12)\n\x06getMap\x12\x0f.api.MapRequest\x1a\x0c.api.MapTest\"\x00\x12\x32\n\tgetMsgMap\x12\x12.api.MsgMapRequest\x1a\x0f.api.MsgMapTest\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPTEST_MAPTESTENTRY._options = None
  _MAPTEST_MAPTESTENTRY._serialized_options = b'8\001'
  _MSGMAPTEST_MSGMAPTESTENTRY._options = None
  _MSGMAPTEST_MSGMAPTESTENTRY._serialized_options = b'8\001'
  _globals['_APIREQUEST']._serialized_start=18
  _globals['_APIREQUEST']._serialized_end=46
  _globals['_ITEMS']._serialized_start=48
  _globals['_ITEMS']._serialized_end=81
  _globals['_MAPREQUEST']._serialized_start=83
  _globals['_MAPREQUEST']._serialized_end=123
  _globals['_MAPTEST']._serialized_start=125
  _globals['_MAPTEST']._serialized_end=226
  _globals['_MAPTEST_MAPTESTENTRY']._serialized_start=180
  _globals['_MAPTEST_MAPTESTENTRY']._serialized_end=226
  _globals['_MSGMAPREQUEST']._serialized_start=228
  _globals['_MSGMAPREQUEST']._serialized_end=282
  _globals['_MSGMAPTEST']._serialized_start=284
  _globals['_MSGMAPTEST']._serialized_end=411
  _globals['_MSGMAPTEST_MSGMAPTESTENTRY']._serialized_start=351
  _globals['_MSGMAPTEST_MSGMAPTESTENTRY']._serialized_end=411
  _globals['_ITEM']._serialized_start=413
  _globals['_ITEM']._serialized_end=445
  _globals['_HELLOREQUEST']._serialized_start=447
  _globals['_HELLOREQUEST']._serialized_end=475
  _globals['_HELLO']._serialized_start=477
  _globals['_HELLO']._serialized_end=501
  _globals['_API']._serialized_start=504
  _globals['_API']._serialized_end=735
# @@protoc_insertion_point(module_scope)
