from enum import Enum

class SpanTypes(Enum):
    CACHE: str = ...
    CASSANDRA: str = ...
    ELASTICSEARCH: str = ...
    GRPC: str = ...
    HTTP: str = ...
    MONGODB: str = ...
    REDIS: str = ...
    SQL: str = ...
    TEMPLATE: str = ...
    TEST: str = ...
    WEB: str = ...
    WORKER: str = ...

class AppTypes:
    def web(cls): ...
    def db(cls): ...
    def cache(cls): ...
    def worker(cls): ...
