from typing import Any, Dict, MutableMapping, Optional

STAGE_NAME: str
JOB_NAME: str
JOB_URL: str
PIPELINE_ID: str
PIPELINE_NAME: str
PIPELINE_NUMBER: str
PIPELINE_URL: str
PROVIDER_NAME: str
WORKSPACE_PATH: str
OS_ARCHITECTURE: str
OS_PLATFORM: str
OS_VERSION: str
RUNTIME_NAME: str
RUNTIME_VERSION: str
log: Any

def tags(env: Optional[MutableMapping[str, str]]=..., cwd: Optional[str]=...) -> Dict[str, str]: ...
def extract_appveyor(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_azure_pipelines(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_bitbucket(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_buildkite(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_circle_ci(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_github_actions(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_gitlab(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_jenkins(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_teamcity(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_travis(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...
def extract_bitrise(env: MutableMapping[str, str]) -> Dict[str, Optional[str]]: ...

PROVIDERS: Any
