from typing import Any, Optional

STAGE_NAME: str
JOB_NAME: str
JOB_URL: str
PIPELINE_ID: str
PIPELINE_NAME: str
PIPELINE_NUMBER: str
PIPELINE_URL: str
PROVIDER_NAME: str
WORKSPACE_PATH: str

def tags(env: Optional[Any] = ...): ...
def extract_appveyor(env: Any): ...
def extract_azure_pipelines(env: Any): ...
def extract_bitbucket(env: Any): ...
def extract_buildkite(env: Any): ...
def extract_circle_ci(env: Any): ...
def extract_github_actions(env: Any): ...
def extract_gitlab(env: Any): ...
def extract_jenkins(env: Any): ...
def extract_teamcity(env: Any): ...
def extract_travis(env: Any): ...
def extract_bitrise(env: Any): ...

PROVIDERS: Any
