"""Contracts for the AppSec-owned WAF submodule of the native extension."""

from typing import Any
from typing import Optional
from typing import TypedDict

class WafEvent(TypedDict, total=False):
    rule: dict[str, Any]
    rule_matches: list[dict[str, Any]]
    span_id: int
    stack_id: str

class EvaluationError(RuntimeError): ...

class Stats:
    def __init__(self) -> None: ...
    @property
    def string_length(self) -> Optional[int]: ...
    @property
    def container_size(self) -> Optional[int]: ...
    @property
    def container_depth(self) -> Optional[int]: ...
    @property
    def nodes(self) -> int: ...
    @property
    def string_bytes(self) -> int: ...
    @property
    def heap_allocations(self) -> int: ...
    @property
    def container_bytes(self) -> int: ...
    def as_dict(self) -> dict[str, Optional[int]]: ...

class Encoded:
    def bytes(self) -> bytes: ...
    def materialize(self) -> Any: ...
    @property
    def stats(self) -> Stats: ...

class Builder:
    def __init__(self) -> None: ...
    def add_config(self, path: str, data: Any) -> tuple[bool, dict[str, Any]]: ...
    def remove_config(self, path: str) -> bool: ...
    def config_paths_count(self, filter_str: Optional[str] = ...) -> int: ...
    def build(self) -> Optional[Engine]: ...

class Engine:
    @staticmethod
    def from_json(json: bytes) -> Engine: ...
    @property
    def required_data(self) -> list[str]: ...
    def context(self) -> Context: ...

class Context:
    def subcontext(self) -> Context: ...
    def run(
        self,
        data: Any,
        timeout_us: int = ...,
        max_objects: int = ...,
        max_depth: int = ...,
        max_string_length: int = ...,
        compatibility: bool = ...,
    ) -> Result: ...

class RulesetInfo:
    def __init__(
        self, version: str, accepted_rules: int, rejected_rules: int, errors: Optional[dict[str, Any]] = ...
    ) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def accepted_rules(self) -> int: ...
    @property
    def rejected_rules(self) -> int: ...
    @property
    def errors(self) -> dict[str, Any]: ...

class Result:
    def __init__(
        self,
        *,
        matched: bool = ...,
        error_code: Optional[int] = ...,
        events: Optional[list[WafEvent]] = ...,
        actions: Optional[dict[str, Any]] = ...,
        duration_ns: int = ...,
        total_duration_ns: int = ...,
        timeout: bool = ...,
        stats: Optional[Stats] = ...,
        attributes: Optional[dict[str, Any]] = ...,
        keep: bool = ...,
    ) -> None: ...
    def prepare(self) -> Result: ...
    @property
    def error_code(self) -> Optional[int]: ...
    @property
    def total_duration_ns(self) -> int: ...
    @property
    def meta_tags(self) -> dict[str, str]: ...
    @property
    def metrics(self) -> dict[str, int | float]: ...
    @property
    def api_security(self) -> dict[str, Any]: ...
    @property
    def matched(self) -> bool: ...
    @property
    def timeout(self) -> bool: ...
    @property
    def keep(self) -> bool: ...
    @property
    def duration_ns(self) -> int: ...
    @property
    def evaluated(self) -> int: ...
    @property
    def stats(self) -> Stats: ...
    @property
    def events(self) -> list[WafEvent]: ...
    @property
    def actions(self) -> dict[str, Any]: ...
    @property
    def attributes(self) -> dict[str, Any]: ...

def version() -> str: ...
def encode(
    data: Any,
    max_objects: int = ...,
    max_depth: int = ...,
    max_string_length: int = ...,
    compatibility: bool = ...,
) -> Encoded: ...
