from typing import List, Dict

class DDSketch:
    def __init__(self): ...
    def add(self, value: float) -> None: ...
    def to_proto(self) -> bytes: ...
    @property
    def count(self) -> float: ...

class PyConfigurator:
    def __init__(self, debug_logs: bool): ...
    def set_envp(self, envp: List[str]) -> None: ...
    def set_args(self, args: List[str]) -> None: ...
    def set_file_override(self, file: str) -> None: ...
    def get_configuration(self) -> Dict[str, str]: ...
