# Generated by Django 4.2.20 on 2025-06-24 06:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "cve_test_item",
            },
        ),
    ]
