from typing import Any

ARGS_NAME: Any
TRACED_ARGS: Any
log: Any

def inject_trace_data_to_message_attributes(trace_data: Any, entry: Any) -> None: ...
def inject_trace_to_sqs_batch_message(args: Any, span: Any) -> None: ...
def inject_trace_to_sqs_message(args: Any, span: Any) -> None: ...
def modify_client_context(client_context_base64: Any, trace_headers: Any): ...
def inject_trace_to_client_context(args: Any, span: Any) -> None: ...
def patch() -> None: ...
def unpatch() -> None: ...
def patched_api_call(original_func: Any, instance: Any, args: Any, kwargs: Any): ...
