from typing import Any

AWS_QUERY_ARGS_NAME: Any
AWS_AUTH_ARGS_NAME: Any
AWS_QUERY_TRACED_ARGS: Any
AWS_AUTH_TRACED_ARGS: Any

def patch() -> None: ...
def unpatch() -> None: ...
def patched_query_request(original_func: Any, instance: Any, args: Any, kwargs: Any): ...
def patched_auth_request(original_func: Any, instance: Any, args: Any, kwargs: Any): ...
