ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV CMAKE_BUILD_PARALLEL_LEVEL=24
ENV PATH=/root/.cargo/bin:$PATH

# Install Rust toolchain
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y
