ARG BASE_IMAGE=quay.io/pypa/musllinux_1_2_i686:latest
FROM ${BASE_IMAGE}

# Install Rust toolchain
RUN apk add --no-cache gcc libgcc libstdc++ llvm15-libs musl musl-dev rust-stdlib && \
    apk add --no-cache rust cargo
