FROM debian:buster-20221219-slim

# Update and install dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install sccache
ENV SCCACHE_VERSION=0.8.1
RUN wget https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz && \
    tar -xzf sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz && \
    mv sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl/sccache /usr/local/bin/ && \
    rm -rf sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz

# Install cppcheck
ENV CPPCHECK_VERSION=2.14.2
RUN wget https://github.com/danmar/cppcheck/archive/refs/tags/${CPPCHECK_VERSION}.tar.gz && \
    tar -xzf ${CPPCHECK_VERSION}.tar.gz && \
    rm -rf ${CPPCHECK_VERSION}.tar.gz && \
    cd cppcheck-${CPPCHECK_VERSION} && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --parallel $(nproc) && \
    cp bin/cppcheck /usr/local/bin/ && \
    cd ../.. && \
    rm -rf cppcheck-${CPPCHECK_VERSION}
