from typing import Any

FILTERS_KEY: str
SAMPLE_RATE_METRIC_KEY: str
SAMPLING_PRIORITY_KEY: str
ANALYTICS_SAMPLE_RATE_KEY: str
SAMPLING_AGENT_DECISION: str
SAMPLING_RULE_DECISION: str
SAMPLING_LIMIT_DECISION: str
ORIGIN_KEY: str
HOSTNAME_KEY: str
ENV_KEY: str
VERSION_KEY: str
SERVICE_KEY: str
SERVICE_VERSION_KEY: str
SPAN_KIND: str
SPAN_MEASURED_KEY: str
KEEP_SPANS_RATE_KEY: str
NUMERIC_TAGS: Any
MANUAL_DROP_KEY: str
MANUAL_KEEP_KEY: str
LOG_SPAN_KEY: str
