import Any
from .internal._encoding import MsgpackEncoder

log: Any

class _EncoderBase:
    def encode_traces(self, traces: builtins.list[builtins.list[ddtrace.span.Span]]) -> str: ...
    def encode_trace(self, trace: builtins.list[ddtrace.span.Span]) -> str: ...
    @staticmethod
    def encode(obj: Any) -> None: ...
    @staticmethod
    def join_encoded(objs: Any) -> None: ...

class JSONEncoder(_EncoderBase):
    content_type: str = ...
    @staticmethod
    def encode(obj: Any) -> str: ...
    @staticmethod
    def join_encoded(objs: builtins.list[builtins.str]) -> str: ...

class JSONEncoderV2(JSONEncoder):
    content_type: str = ...
    def encode_traces(self, traces: builtins.list[builtins.list[ddtrace.span.Span]]) -> str: ...
    def encode_trace(self, trace: builtins.list[ddtrace.span.Span]) -> str: ...
    @staticmethod
    def join_encoded(objs: builtins.list[builtins.str]) -> str: ...
Encoder = MsgpackEncoder
