from typing import Any, List

log: Any
PATCH_MODULES: Any

class PatchException(Exception): ...
class ModuleNotFoundException(PatchException): ...

def patch_all(**patch_modules: builtins.dict[builtins.str, builtins.bool]) -> None: ...
def patch(raise_errors: builtins.bool=..., **patch_modules: builtins.dict[builtins.str, builtins.bool]) -> None: ...
def patch_module(module: builtins.str, raise_errors: builtins.bool=...) -> bool: ...
def get_patched_modules() -> List[str]: ...
