from typing import Any, Dict, List

log: Any
PATCH_MODULES: Any

class PatchException(Exception): ...
class ModuleNotFoundException(PatchException): ...

def patch_all(**patch_modules: Dict[str, bool]) -> None: ...
def patch(raise_errors: bool=..., **patch_modules: Dict[str, bool]) -> None: ...
def patch_module(module: str, raise_errors: bool=...) -> bool: ...
def get_patched_modules() -> List[str]: ...
