from .utils.deprecation import RemovedInDDTrace10Warning as RemovedInDDTrace10Warning
from .vendor.debtcollector.removals import removed_property as removed_property
from typing import Any, Union

class PayloadFull(Exception): ...

class Payload:
    DEFAULT_MAX_PAYLOAD_SIZE: Any = ...
    max_payload_size: Any = ...
    traces: builtins.list[builtins.bytes] = ...
    size: int = ...
    def __init__(self, encoder: Union[ddtrace.internal._encoding.MsgpackEncoder, None]=..., max_payload_size: builtins.int=...) -> None: ...
    def add_trace(self, trace: Union[builtins.list[ddtrace.span.Span], None]) -> None: ...
    @property
    def length(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    def get_payload(self) -> Union[str, bytes]: ...
