import Any
import abc

log: Any
MAX_TRACE_ID: Any
KNUTH_FACTOR: int

class BaseSampler(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def sample(self, span: Any) -> Any: ...

class BasePrioritySampler(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def update_rate_by_service_sample_rates(self, sample_rates: Any) -> Any: ...

class AllSampler(BaseSampler):
    def sample(self, span: ddtrace.span.Span) -> bool: ...

class RateSampler(BaseSampler):
    def __init__(self, sample_rate: builtins.float=...) -> None: ...
    sample_rate: Any = ...
    sampling_id_threshold: Any = ...
    def set_sample_rate(self, sample_rate: builtins.float) -> None: ...
    def sample(self, span: ddtrace.span.Span) -> bool: ...

class RateByServiceSampler(BaseSampler, BasePrioritySampler):
    sample_rate: Any = ...
    def __init__(self, sample_rate: builtins.float=...) -> None: ...
    def set_sample_rate(self, sample_rate: builtins.float, service: builtins.str=..., env: builtins.str=...) -> None: ...
    def sample(self, span: ddtrace.span.Span) -> bool: ...
    def update_rate_by_service_sample_rates(self, rate_by_service: builtins.dict[builtins.str, builtins.float]) -> None: ...

class DatadogSampler(BaseSampler, BasePrioritySampler):
    NO_RATE_LIMIT: int = ...
    DEFAULT_RATE_LIMIT: int = ...
    rules: Any = ...
    limiter: Any = ...
    default_sampler: Any = ...
    def __init__(self, rules: Union[builtins.list[ddtrace.sampler.SamplingRule], None]=..., default_sample_rate: Union[builtins.float, None]=..., rate_limit: Union[builtins.int, None]=...) -> None: ...
    def update_rate_by_service_sample_rates(self, sample_rates: builtins.dict[builtins.str, builtins.float]) -> None: ...
    def sample(self, span: ddtrace.span.Span) -> bool: ...

class SamplingRule(BaseSampler):
    NO_RULE: Any = ...
    service: Any = ...
    name: Any = ...
    def __init__(self, sample_rate: builtins.float, service: Any=..., name: Any=...) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, sample_rate: float) -> None: ...
    def matches(self, span: ddtrace.span.Span) -> bool: ...
    def sample(self, span: ddtrace.span.Span) -> bool: ...
