import Any
from .context import Context
from .internal.compat import NumericType
from .tracer import Tracer
from typing import Callable, Dict, List, Optional, Text, Union

log: Any

class Span:
    name: Any = ...
    service: Any = ...
    resource: Any = ...
    meta: builtins.dict[Union[builtins.str, builtins.bytes], builtins.str] = ...
    error: int = ...
    metrics: builtins.dict[Union[builtins.str, builtins.bytes], Union[builtins.int, builtins.float]] = ...
    start_ns: Any = ...
    duration_ns: Union[builtins.int, None] = ...
    trace_id: builtins.int = ...
    span_id: builtins.int = ...
    parent_id: Union[builtins.int, None] = ...
    tracer: Union[ddtrace.tracer.Tracer, None] = ...
    sampled: builtins.bool = ...
    def __init__(self, tracer: Optional[Tracer], name: str, service: Optional[str]=..., resource: Optional[str]=..., span_type: Optional[str]=..., trace_id: Optional[int]=..., span_id: Optional[int]=..., parent_id: Optional[int]=..., start: Optional[int]=..., context: Optional[Context]=..., on_finish: Optional[List[Callable[[Span], None]]]=...) -> None: ...
    @property
    def start(self) -> float: ...
    @start.setter
    def start(self, value: Union[int, float]) -> None: ...
    @property
    def span_type(self): ...
    @span_type.setter
    def span_type(self, value: Any) -> None: ...
    @property
    def finished(self) -> bool: ...
    @finished.setter
    def finished(self, value: bool) -> None: ...
    @property
    def duration(self) -> Optional[float]: ...
    @duration.setter
    def duration(self, value: float) -> None: ...
    def finish(self, finish_time: Optional[float]=...) -> None: ...
    def set_tag(self, key: _TagNameType, value: Any=...) -> None: ...
    def get_tag(self, key: _TagNameType) -> Optional[Text]: ...
    def set_tags(self, tags: _MetaDictType) -> None: ...
    def set_meta(self, k: _TagNameType, v: NumericType) -> None: ...
    def set_metas(self, kvs: _MetaDictType) -> None: ...
    def set_metric(self, key: _TagNameType, value: NumericType) -> None: ...
    def set_metrics(self, metrics: _MetricDictType) -> None: ...
    def get_metric(self, key: _TagNameType) -> Optional[NumericType]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def set_traceback(self, limit: int=...) -> None: ...
    def set_exc_info(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def pprint(self) -> str: ...
    @property
    def context(self) -> Context: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
