from types import ModuleType

ops: ModuleType
aspects: ModuleType

def initialize_native_state() -> None: ...
def reset_native_state() -> None: ...
def reset_source_truncation_cache() -> None: ...
def reset_taint_range_limit_cache() -> None: ...
