from typing import Any

def _aspect_ospathbasename(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathdirname(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathjoin(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathnormcase(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathsplit(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathsplitdrive(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathsplitext(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_ospathsplitroot(*args: Any, **kwargs: Any) -> Any: ...
