from typing import Any

def _aspect_rsplit(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_split(*args: Any, **kwargs: Any) -> Any: ...
def _aspect_splitlines(*args: Any, **kwargs: Any) -> Any: ...
