from typing import Any

from .taint_tracking import TaintRange_

def _convert_escaped_text_to_tainted_text(*args: Any, **kwargs: Any) -> Any: ...
def are_all_text_all_ranges(*args: Any, **kwargs: Any) -> tuple[list[TaintRange_], list[TaintRange_]]: ...
def as_formatted_evidence(*args: Any, **kwargs: Any) -> Any: ...
def common_replace(*args: Any, **kwargs: Any) -> Any: ...
def parse_params(*args: Any, **kwargs: Any) -> Any: ...
def set_ranges_on_splitted(*args: Any, **kwargs: Any) -> Any: ...
