from typing import Optional

def clear_all_request_context_slots() -> None: ...
def debug_context_array_free_slots_number() -> int: ...
def debug_context_array_size() -> int: ...
def debug_num_tainted_objects(context_id: int) -> int: ...
def debug_taint_map(context_id: int) -> str: ...
def finish_request_context(context_id: int) -> None: ...
def is_in_taint_map(candidate: object, context_id: int) -> bool: ...
def start_request_context() -> Optional[int]: ...
