DD_TRACE_CTX = "_dd_trace_ctx"

RAY_SUBMISSION_ID = "_RAY_SUBMISSION_ID"
RAY_JOB_ID = "ray.job_id"
RAY_NODE_ID = "ray.node_id"
RAY_PID = "ray.pid"
RAY_WORKER_ID = "ray.worker_id"
RAY_TASK_ID = "ray.task_id"
RAY_ACTOR_ID = "ray.actor_id"
RAY_SUBMISSION_ID_TAG = "ray.submission_id"
