FROM python:3.10-bullseye
# JJJ REMOVE THIS FILE!

# set work directory
WORKDIR /app


# dependencies for psycopg2
RUN apt-get update && apt-get install --no-install-recommends -y curl dnsutils cmake git libpq-dev python3-dev libyaml-dev build-essential \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# rust
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y
ENV PATH=/root/.cargo/bin:$PATH

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Download pygoat
RUN git clone https://github.com/adeyosemanputra/pygoat.git


# copy project
COPY tests/appsec/integrations/pygoat_tests /app/

# pip install some deps
RUN python3 -m pip install --no-cache-dir pip==22.0.4
RUN pip install --no-cache-dir setuptools-rust cmake cython==0.29.32

# Copy ddtrace
WORKDIR /
COPY . /ddtrace

# Clear any existing CMake and build cache and rebuild
RUN rm -rf /ddtrace/build
RUN find / -name "CMakeCache.txt" -exec rm -f {} \;


# Install ddtrace
WORKDIR /ddtrace
RUN pip install --no-cache-dir .

WORKDIR /app/pygoat
# Install dependencies
RUN git checkout v2.0.1
# Install the app requirements
RUN pip install --no-cache-dir -r requirements.txt

# At some point, pyyaml started failing on CI with CBaseLoader import error, this
# fixed the problem
RUN pip install --no-cache-dir --force-reinstall  pyyaml==6.0.1 --global-option="--without-libyaml"

# install pygoat
EXPOSE 8321

# Note: admin login from the fixtures is "admin/adminpassword"
RUN python3 manage.py migrate
RUN python3 manage.py loaddata ../fixtures/*
CMD ["ddtrace-run", "python3", "manage.py", "runserver", "0.0.0.0:8321"]
