import types
import typing

from ddtrace.profiling import collector
from ddtrace.trace import Tracer

ACQUIRE_RELEASE_CO_NAMES: frozenset[str]
ENTER_EXIT_CO_NAMES: frozenset[str]

def _get_original_lock_class(module_name: str, class_name: str) -> typing.Callable[..., typing.Any]: ...
def _create_original_lock_instance(module_name: str, class_name: str) -> typing.Any: ...

class _ProfiledLock:
    __wrapped__: typing.Any
    tracer: typing.Optional[Tracer]
    capture_sampler: collector.CaptureSampler
    init_location: str
    acquired_time: typing.Optional[int]
    name: typing.Optional[str]
    is_internal: bool

    def __init__(
        self,
        wrapped: typing.Any,
        tracer: typing.Optional[Tracer],
        capture_sampler: collector.CaptureSampler,
        is_internal: bool = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getattr__(self, name: str) -> typing.Any: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[typing.Callable[[str, str], typing.Any], tuple[str, str]]: ...
    def locked(self) -> bool: ...
    def acquire(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __enter__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __aenter__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def _acquire(
        self, inner_func: typing.Callable[..., typing.Any], *args: typing.Any, **kwargs: typing.Any
    ) -> typing.Any: ...
    def release(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __exit__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def __aexit__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def _release(
        self, inner_func: typing.Callable[..., typing.Any], *args: typing.Any, **kwargs: typing.Any
    ) -> None: ...
    def _flush_sample(self, start: int, end: int, is_acquire: bool) -> None: ...
    def _find_name(self, var_dict: dict[str, typing.Any]) -> typing.Optional[str]: ...
    def _update_name(self) -> None: ...

class _LockAllocatorWrapper:
    _func: typing.Callable[..., _ProfiledLock]
    _original_class: typing.Optional[type[typing.Any]]

    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def __call__(self, *args: typing.Any, **kwargs: typing.Any) -> _ProfiledLock: ...
    def __get__(
        self, instance: typing.Any, owner: typing.Optional[type[typing.Any]] = ...
    ) -> _LockAllocatorWrapper: ...
    def __getattr__(self, name: str) -> typing.Any: ...
    def __or__(self, other: typing.Optional[type[typing.Any]]) -> typing.Any: ...
    def __ror__(self, other: typing.Optional[type[typing.Any]]) -> typing.Any: ...
    def __mro_entries__(self, bases: tuple[typing.Any, ...]) -> tuple[type[typing.Any], ...]: ...
    def __reduce__(
        self,
    ) -> tuple[typing.Callable[[str, str], typing.Callable[..., typing.Any]], tuple[str, str]]: ...

class LockCollector(collector.CaptureSamplerCollector):
    PROFILED_LOCK_CLASS: type[_ProfiledLock]
    MODULE: types.ModuleType
    PATCHED_LOCK_NAME: str
    INTERNAL_MODULE_FILE: typing.Optional[str]
    tracer: typing.Optional[Tracer]
    _original_lock: typing.Optional[typing.Callable[..., typing.Any]]

    def __init__(self, tracer: typing.Optional[Tracer] = ..., *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def _get_patch_target(self) -> typing.Callable[..., typing.Any]: ...
    def _set_patch_target(
        self, value: typing.Union[_LockAllocatorWrapper, typing.Callable[..., typing.Any], None]
    ) -> None: ...
    def _start_service(self) -> None: ...
    def _stop_service(self) -> None: ...
    def patch(self) -> None: ...
    def unpatch(self) -> None: ...
