import types
import typing

from ddtrace.profiling import collector
from ddtrace.trace import Tracer

class _ProfiledLock:
    __wrapped__: typing.Any
    tracer: typing.Optional[Tracer]
    capture_sampler: collector.CaptureSampler
    init_location: str
    acquired_time: typing.Optional[int]
    name: typing.Optional[str]
    is_internal: bool

    def __init__(
        self,
        wrapped: typing.Any,
        tracer: typing.Optional[Tracer],
        capture_sampler: collector.CaptureSampler,
        is_internal: bool = ...,
    ) -> None: ...
    def acquire(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def release(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def locked(self) -> bool: ...
    def __enter__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __exit__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def __aenter__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __aexit__(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def __getattr__(self, name: str) -> typing.Any: ...
    def __eq__(self, other: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[typing.Callable[..., typing.Any], tuple[str, str]]: ...

class _LockAllocatorWrapper:
    _func: typing.Callable[..., _ProfiledLock]
    _original_class: typing.Optional[type[typing.Any]]

    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def __call__(self, *args: typing.Any, **kwargs: typing.Any) -> _ProfiledLock: ...
    def __get__(self, instance: typing.Any, owner: typing.Optional[type] = ...) -> _LockAllocatorWrapper: ...
    def __getattr__(self, name: str) -> typing.Any: ...
    def __or__(self, other: typing.Optional[type[typing.Any]]) -> typing.Any: ...
    def __ror__(self, other: typing.Optional[type[typing.Any]]) -> typing.Any: ...
    def __mro_entries__(self, bases: tuple[typing.Any, ...]) -> tuple[type[typing.Any], ...]: ...
    def __reduce__(self) -> tuple[typing.Callable[..., typing.Any], tuple[str, str]]: ...

class LockCollector(collector.CaptureSamplerCollector):
    PROFILED_LOCK_CLASS: type[typing.Any]
    MODULE: types.ModuleType
    PATCHED_LOCK_NAME: str
    INTERNAL_MODULE_FILE: typing.Optional[str]
    tracer: typing.Optional[Tracer]

    def __init__(self, tracer: typing.Optional[Tracer] = ..., *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def _get_patch_target(self) -> typing.Callable[..., typing.Any]: ...
    def _set_patch_target(self, value: typing.Any) -> None: ...
    def _start_service(self) -> None: ...
    def _stop_service(self) -> None: ...
    def patch(self) -> None: ...
    def unpatch(self) -> None: ...
