from typing import Optional
from typing import TypedDict

class _CodeCacheStats(TypedDict):
    hits: int
    misses: int
    evictions: int
    capacity: int

def start(max_nframe: int, heap_sample_interval: int, mem_domain_enabled: bool, code_cache_size: int) -> None: ...
def stop() -> None: ...
def heap() -> None: ...
def code_cache_stats() -> Optional[_CodeCacheStats]: ...
def code_cache_per_set_stats() -> Optional[list[int]]: ...
def code_cache_reset_counters() -> None: ...
def code_cache_disable() -> None: ...
def code_cache_enable(capacity: int = ...) -> None: ...
