class CaptureSampler:
    capture_pct: float
    _counter: float
    _bypass: bool

    def __init__(self, capture_pct: float = ...) -> None: ...
    def __repr__(self) -> str: ...
    def set_bypass(self, value: bool) -> None: ...
    def capture(self) -> bool: ...
