import types
import typing

def task_object_address(task: object) -> int: ...
def initialize_gevent_support() -> None: ...
def get_task() -> tuple[typing.Optional[int], typing.Optional[str], typing.Optional[types.FrameType]]: ...
