from .._types import StringType, ValueType
from typing import Dict

def set_args(args: list[str]) -> None: ...
def set_envp(args: list[str]) -> None: ...
def get_config(debug_logs: bool) -> Dict[str, ValueType]: ...
