import Any
from typing import Optional

log: Any
DEFAULTS: Any
IMPORT_STRINGS: Any
REMOVED_SETTINGS: Any

def import_from_string(val: Any, setting_name: Any): ...

class DatadogSettings:
    defaults: Any = ...
    import_strings: Any = ...
    def __init__(self, user_settings: Optional[Any] = ..., defaults: Optional[Any] = ..., import_strings: Optional[Any] = ...) -> None: ...
    @property
    def user_settings(self) -> Any: ...
    def __getattr__(self, attr: Any): ...

settings: Any

def reload_settings(*args: Any, **kwargs: Any) -> None: ...
def configure_from_settings(pin: Any, config: Any, settings: Any) -> None: ...
