from typing import Any, Optional

log: Any
Resolver404: Any
DJANGO22: Any

def patch_conn(django: Any, conn: Any): ...
def instrument_dbs(django: Any): ...
def traced_cache(django: Any, pin: Any, func: Any, instance: Any, args: Any, kwargs: Any): ...
def instrument_caches(django: Any) -> None: ...
def traced_populate(django: Any, pin: Any, func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_func(django: Any, name: Any, resource: Optional[Any] = ..., ignored_excs: Optional[Any] = ...): ...
def traced_process_exception(django: Any, name: Any, resource: Optional[Any] = ...): ...
def traced_load_middleware(django: Any, pin: Any, func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_get_response(django: Any, pin: Any, func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_template_render(django: Any, pin: Any, wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def instrument_view(django: Any, view: Any): ...
def traced_urls_path(django: Any, pin: Any, wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_as_view(django: Any, pin: Any, func: Any, instance: Any, args: Any, kwargs: Any): ...
def patch() -> None: ...
def unpatch() -> None: ...
