from typing import Any

log: Any

def resource_from_cache_prefix(resource: Any, cache: Any): ...
def quantize_key_values(key: Any): ...
def get_django_2_route(request: Any, resolver_match: Any): ...
def set_tag_array(span: Any, prefix: Any, value: Any) -> None: ...
def get_request_uri(request: Any): ...
