ALLOWED_FIRST_PARTY_ALLOWLIST: int
ALLOWED_STATIC_ALLOWLIST: int
ALLOWED_USER_ALLOWLIST: int
DENIED_BUILTINS_DENYLIST: int
DENIED_NOT_FOUND: int
DENIED_STATIC_DENYLIST: int
DENIED_USER_DENYLIST: int

def build_list_from_env(env_var_name: str) -> bool: ...
def get_user_allowlist() -> list[str]: ...
def should_iast_patch(module_name: str) -> int: ...
def set_packages_distributions(packages: set[str]) -> None: ...
