import asyncio

def register_thread(id: int, native_id: int, name: str) -> None: ...
def unregister_thread(name: str) -> None: ...
def track_asyncio_loop(thread_id: int, loop: asyncio.EventLoop) -> None: ...
def link_tasks(parent: asyncio.EventLoop, child: asyncio.Task) -> None: ...

is_available: bool
failure_msg: str
