# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.internal.azure_eventhub.patch import get_version
from ddtrace.contrib.internal.azure_eventhub.patch import patch


try:
    from ddtrace.contrib.internal.azure_eventhub.patch import unpatch
except ImportError:
    unpatch = None
from tests.contrib.patch import PatchTestCase


class TestAzureEventHubPatch(PatchTestCase.Base):
    __integration_name__ = "azure_eventhub"
    __module_name__ = "azure.eventhub"
    __patch_func__ = patch
    __unpatch_func__ = unpatch
    __get_version__ = get_version

    def assert_module_patched(self, azure_eventhub):
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.send_batch)

    def assert_not_module_patched(self, azure_eventhub):
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.send_batch)

    def assert_not_module_double_patched(self, azure_eventhub):
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.send_batch)


class TestAzureEventHubAioPatch(PatchTestCase.Base):
    __integration_name__ = "azure_eventhub"
    __module_name__ = "azure.eventhub.aio"
    __patch_func__ = patch
    __unpatch_func__ = unpatch
    __get_version__ = get_version

    def assert_module_patched(self, azure_eventhub):
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_wrapped(azure_eventhub.EventHubProducerClient.send_batch)

    def assert_not_module_patched(self, azure_eventhub):
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_not_wrapped(azure_eventhub.EventHubProducerClient.send_batch)

    def assert_not_module_double_patched(self, azure_eventhub):
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.__init__)
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.send_event)
        self.assert_not_double_wrapped(azure_eventhub.EventHubProducerClient.send_batch)
