from typing import Any, Optional

log: Any

class PylonsTraceMiddleware:
    app: Any = ...
    def __init__(self, app: Any, tracer: Any, service: str = ..., distributed_tracing: Optional[Any] = ...) -> None: ...
    def __call__(self, environ: Any, start_response: Any): ...
