from ...propagation.http import HTTPPropagator
from typing import Any

propagator = HTTPPropagator

def patch() -> None: ...
def unpatch() -> None: ...
def traced_receive(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_publish(func: Any, instance: Any, args: Any, kwargs: Any): ...
