from typing import Any

PUBLISH_BODY_IDX: int
PUBLISH_ROUTING_KEY: int
PUBLISH_EXCHANGE_IDX: int
HEADER_POS: int

def extract_conn_tags(connection: Any): ...
def get_exchange_from_args(args: Any): ...
def get_routing_key_from_args(args: Any): ...
def get_body_length_from_args(args: Any): ...
