from typing import Any, Optional

log: Any
OP_CODES: Any
MAX_MSG_PARSE_LEN: Any
header_struct: Any

class Command:
    name: Any = ...
    coll: Any = ...
    db: Any = ...
    tags: Any = ...
    metrics: Any = ...
    query: Any = ...
    def __init__(self, name: Any, db: Any, coll: Any) -> None: ...

def parse_msg(msg_bytes: Any): ...
def parse_query(query: Any): ...
def parse_spec(spec: Any, db: Optional[Any] = ...): ...
