import Any

def patch() -> None: ...
def unpatch() -> None: ...
def trace_mongo_client(client: Any, tracer: Any, service: Any = ...) -> Any: ...
def patch_pymongo_module() -> None: ...
def unpatch_pymongo_module() -> None: ...
def traced_get_socket(wrapped: Any, instance: Any, args: Any, kwargs: Any) -> None: ...
