#!/bin/sh
staged_files=$(git diff --staged --name-only HEAD --diff-filter=ACMR | grep -E '\.py$' | tr '\n' ' ')
if [ -n "$staged_files" ]; then
    file_count=$(echo "$staged_files" | wc -w | tr -d ' ')
    echo "Running ast-grep on $file_count staged Python file(s)..."
    hatch -v run lint:sg -- $staged_files
else
    echo 'Run ast-grep skipped: No Python files were found in `git diff --staged`'
fi
