import Any
from typing import Optional

class removed_classproperty(property):
    def __get__(self, cls: Type[Any], owner: Type[Any]) -> Any: ...

class ArgumentError(Exception): ...

def get_argument_value(args: builtins.list[Any], kwargs: builtins.dict[builtins.str, Any], pos: builtins.int, kw: builtins.str) -> Optional[Any]: ...
