from typing import Any, Callable, Optional

class RemovedInDDTrace10Warning(DeprecationWarning): ...

def format_message(name: builtins.str, message: builtins.str, version: Union[builtins.str, None]=...) -> str: ...
def warn(message: builtins.str, stacklevel: builtins.int=...) -> None: ...
def deprecation(name: builtins.str=..., message: builtins.str=..., version: Union[builtins.str, None]=...) -> None: ...
def deprecated(message: builtins.str=..., version: Union[builtins.str, None]=...) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def get_service_legacy(default: Union[builtins.str, None]=...) -> Optional[str]: ...
