from typing import Any, Callable, Optional

class RemovedInDDTrace10Warning(DeprecationWarning): ...

def format_message(name: str, message: str, version: Optional[str]=...) -> str: ...
def warn(message: str, stacklevel: int=...) -> None: ...
def deprecation(name: str=..., message: str=..., version: Optional[str]=...) -> None: ...
def deprecated(message: str=..., version: Optional[str]=...) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def get_service_legacy(default: Optional[str]=...) -> Optional[str]: ...
