from typing import Any, Optional

class RemovedInDDTrace10Warning(DeprecationWarning): ...

def format_message(name: Any, message: Any, version: Any): ...
def warn(message: Any, stacklevel: int = ...) -> None: ...
def deprecation(name: str = ..., message: str = ..., version: Optional[Any] = ...) -> None: ...
def deprecated(message: str = ..., version: Optional[Any] = ...): ...
def get_service_legacy(default: Optional[Any] = ...): ...
