import Any
from typing import Dict, Optional, TypeVar, Union

T = TypeVar('T')
log: Any

def get_env(*parts: builtins.str, **kwargs: T`-1) -> Union[str, T, None]: ...
def deep_getattr(obj: Any, attr_string: builtins.str, default: Union[Any, None]=...) -> Optional[Any]: ...
def asbool(value: Union[builtins.str, builtins.bool, None]) -> bool: ...
def parse_tags_str(tags_str: builtins.str) -> Dict[str, str]: ...
