from typing import Any, Optional

log: Any

def get_env(*parts: Any, **kwargs: Any): ...
def deep_getattr(obj: Any, attr_string: Any, default: Optional[Any] = ...): ...
def asbool(value: Any): ...
def parse_tags_str(tags_str: Any): ...
