import Any
from typing import Dict, Optional, TypeVar, Union

T = TypeVar('T')
log: Any

def get_env(*parts: str, **kwargs: T) -> Union[str, T, None]: ...
def deep_getattr(obj: Any, attr_string: str, default: Optional[Any]=...) -> Optional[Any]: ...
def asbool(value: Union[str, bool, None]) -> bool: ...
def parse_tags_str(tags_str: str) -> Dict[str, str]: ...
