import Any
from typing import List

class require_modules:
    def __init__(self, modules: builtins.list[builtins.str]) -> None: ...
    def __enter__(self) -> List[str]: ...
    def __exit__(self, exc_type: Union[Type[builtins.BaseException], None], exc_value: Union[builtins.BaseException, None], traceback: Union[types.TracebackType, None]) -> None: ...

def func_name(f: def (*Any, **Any) -> Any) -> str: ...
def module_name(instance: Any) -> str: ...
