from types import TracebackType
from typing import Any, Callable, List, Optional, Type

class require_modules:
    def __init__(self, modules: List[str]) -> None: ...
    def __enter__(self) -> List[str]: ...
    def __exit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...

def func_name(f: Callable[..., Any]) -> str: ...
def module_name(instance: Any) -> str: ...
