from typing import Any

class require_modules:
    def __init__(self, modules: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any): ...

def func_name(f: Any): ...
def module_name(instance: Any): ...
