from typing import Any

class StopWatch:
    def __init__(self) -> None: ...
    def start(self): ...
    def elapsed(self): ...
    def __enter__(self): ...
    def __exit__(self, tp: Any, value: Any, traceback: Any) -> None: ...
    def stop(self): ...
