from types import TracebackType
from typing import Optional, Type

class StopWatch:
    def __init__(self) -> None: ...
    def start(self) -> StopWatch: ...
    def elapsed(self) -> float: ...
    def __enter__(self) -> StopWatch: ...
    def __exit__(self, tp: Optional[Type[BaseException]], value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
    def stop(self) -> StopWatch: ...
