class StopWatch:
    def __init__(self) -> None: ...
    def start(self) -> StopWatch: ...
    def elapsed(self) -> float: ...
    def __enter__(self) -> StopWatch: ...
    def __exit__(self, tp: Union[Type[builtins.BaseException], None], value: Union[builtins.BaseException, None], traceback: Union[types.TracebackType, None]) -> None: ...
    def stop(self) -> StopWatch: ...
