from typing import Any, Optional

def iswrapped(obj: Any, attr: Optional[Any] = ...): ...
def unwrap(obj: Any, attr: Any) -> None: ...
def safe_patch(patchable: Any, key: Any, patch_func: Any, service: Any, meta: Any, tracer: Any): ...
