import Any
import ddtrace
from typing import Callable, TypeVar

F = TypeVar('F', bound=Callable[..., Any])

def iswrapped(obj: Any, attr: Union[builtins.str, None]=...) -> bool: ...
def unwrap(obj: Any, attr: builtins.str) -> None: ...
def safe_patch(patchable: Any, key: Any, patch_func: Callable[[F, str, dict, ddtrace.Tracer], F], service: str, meta: dict, tracer: ddtrace.Tracer) -> None: ...
