VULN_INSECURE_HASHING_TYPE = "WEAK_HASH"
VULN_WEAK_CIPHER_TYPE = "WEAK_CIPHER"

EVIDENCE_ALGORITHM_TYPE = "ALGORITHM"

MD5_DEF = "md5"
SHA1_DEF = "sha1"

DEFAULT_WEAK_HASH_ALGORITHMS = (MD5_DEF, SHA1_DEF)
