import Any

log: Any
RESOURCE_MAX_LENGTH: int
SERVICE: str
CURRENT_SPAN: str
PAGE_NUMBER: str

def patch() -> None: ...
def unpatch() -> None: ...
def traced_connect(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_set_final_result(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_set_final_exception(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_start_fetching_next_page(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_execute_async(func: Any, instance: Any, args: Any, kwargs: Any): ...
def get_traced_cassandra(*args: Any, **kwargs: Any) -> Any: ...
