from typing import Any, Optional

def trace_engine(engine: Any, tracer: Optional[Any] = ..., service: Optional[Any] = ...) -> None: ...

class EngineTracer:
    tracer: Any = ...
    engine: Any = ...
    vendor: Any = ...
    service: Any = ...
    name: Any = ...
    def __init__(self, tracer: Any, service: Any, engine: Any) -> None: ...
