#!/usr/bin/env bash
set -euo pipefail

scripts/test-env lock "$@"

echo "Generating supported versions from uv lockfiles"
scripts/integration_registry/generate_supported_versions.py

echo "All done!"
