#!/usr/bin/env scripts/uv-run-script
# -*- mode: python -*-
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///
"""
Creates GitHub issues for nightly CI failures.

Handles deduplication, assignee detection, and auto-resolution.
Uses the gh CLI for GitHub API interaction.
"""

import argparse
from datetime import datetime
import json
import os
import subprocess
import sys
from typing import List
from typing import Optional


LABEL_NIGHTLY_FAILURE = "ci-nightly-failure"
LABEL_CI = "ci"
LABEL_INFRASTRUCTURE = "infrastructure"


def run_gh_command(cmd: List[str]) -> subprocess.CompletedProcess:
    """Run gh CLI command and return result."""
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result
    except subprocess.CalledProcessError as e:
        print(f"Error running gh command: {e}", file=sys.stderr)
        print(f"stdout: {e.stdout}", file=sys.stderr)
        print(f"stderr: {e.stderr}", file=sys.stderr)
        raise


def search_existing_issue(branch: str) -> Optional[str]:
    """Check if open incident exists for this branch."""
    query = f"is:issue is:open label:{LABEL_NIGHTLY_FAILURE} '{branch}' in:title"

    try:
        cmd = ["gh", "issue", "list", "--search", query, "--json", "number,title", "--limit", "1"]
        result = run_gh_command(cmd)

        issues = json.loads(result.stdout)
        return str(issues[0]["number"]) if issues else None
    except Exception as e:
        print(f"Error searching for existing issue: {e}", file=sys.stderr)
        return None


def get_codeowners_team() -> str:
    """Get default team from CODEOWNERS."""
    # From .github/CODEOWNERS line 4: * @DataDog/apm-core-python
    return "DataDog/apm-core-python"


def generate_issue_body(branch: str, failed_jobs: List[dict], workflow_url: str) -> str:
    """Generate markdown issue body."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    jobs_section = "\n".join([f"- **{job['name']}** ([logs]({job['url']}))" for job in failed_jobs])

    return f"""## Nightly CI Failure: Branch `{branch}`

The nightly CI monitor detected failures on branch `{branch}`.

### Failed Jobs

{jobs_section}

### Investigation

- **Workflow Run:** {workflow_url}
- **Branch:** `{branch}`
- **Detected:** {timestamp}

### Next Steps

1. Review the failed job logs above
2. Determine if this is a flaky test or genuine failure
3. If genuine failure, branch cannot release until fixed
4. If flaky, consider adding @flaky decorator or fixing root cause

### Auto-Resolution

This issue will auto-close when the branch passes nightly CI validation.

---
*Auto-generated by nightly-branch-monitor workflow*
"""


def create_issue(branch: str, failed_jobs: List[dict], workflow_url: str) -> str:
    """Create new GitHub issue."""
    title = f"[CI Nightly] Branch {branch} failing"
    body = generate_issue_body(branch, failed_jobs, workflow_url)
    team = get_codeowners_team()

    labels = [LABEL_NIGHTLY_FAILURE, LABEL_CI, LABEL_INFRASTRUCTURE]

    cmd = ["gh", "issue", "create", "--title", title, "--body", body, "--label", ",".join(labels)]

    # Try to assign to team (may fail if team assignment not allowed)
    try:
        result = run_gh_command(cmd)
        issue_url = result.stdout.strip()

        # Attempt to assign team in a comment (mention)
        issue_number = issue_url.split("/")[-1]
        comment = f"Assigning to @{team} for investigation."
        comment_cmd = ["gh", "issue", "comment", issue_number, "--body", comment]
        run_gh_command(comment_cmd)

        return issue_url
    except Exception as e:
        print(f"Error creating issue: {e}", file=sys.stderr)
        raise


def update_issue(issue_number: str, failed_jobs: List[dict], workflow_url: str):
    """Add comment to existing issue."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    jobs_section = "\n".join([f"- **{job['name']}** ([logs]({job['url']}))" for job in failed_jobs])

    comment = f"""### Still Failing ({timestamp})

The branch is still failing nightly CI validation.

**Failed Jobs:**
{jobs_section}

**Workflow Run:** {workflow_url}
"""

    cmd = ["gh", "issue", "comment", issue_number, "--body", comment]
    run_gh_command(cmd)


def close_resolved_issue(branch: str):
    """Close issue if branch is now passing."""
    issue_number = search_existing_issue(branch)

    if not issue_number:
        return  # No open issue to close

    comment = f"""### Resolved

Branch `{branch}` is now passing nightly CI validation.

Auto-closing this issue.
"""

    # Add comment
    cmd = ["gh", "issue", "comment", issue_number, "--body", comment]
    run_gh_command(cmd)

    # Close issue
    cmd = ["gh", "issue", "close", issue_number]
    run_gh_command(cmd)


def main():
    parser = argparse.ArgumentParser(description="Create or update CI incident")
    parser.add_argument("--branch", required=True, help="Branch name")
    parser.add_argument("--failed-jobs", help="JSON array of failed jobs")
    parser.add_argument("--workflow-url", help="Workflow run URL")
    parser.add_argument("--resolved", action="store_true", help="Close issue if branch passing")

    args = parser.parse_args()

    if args.resolved:
        close_resolved_issue(args.branch)
        print(f"Closed incident for branch {args.branch}")
        return 0

    if not args.failed_jobs or not args.workflow_url:
        print("Error: --failed-jobs and --workflow-url required when not using --resolved", file=sys.stderr)
        return 1

    # Parse failed jobs JSON
    try:
        failed_jobs = json.loads(args.failed_jobs)
    except json.JSONDecodeError as e:
        print(f"Error parsing failed-jobs JSON: {e}", file=sys.stderr)
        return 1

    # Check for existing incident
    existing = search_existing_issue(args.branch)

    if existing:
        update_issue(existing, failed_jobs, args.workflow_url)
        print(f"Updated existing issue #{existing}")
        repo = os.environ.get("GITHUB_REPOSITORY", "DataDog/dd-trace-py")
        print(f"issue_url=https://github.com/{repo}/issues/{existing}")
    else:
        issue_url = create_issue(args.branch, failed_jobs, args.workflow_url)
        print(f"Created new issue: {issue_url}")
        print(f"issue_url={issue_url}")

    return 0


if __name__ == "__main__":
    # sys.exit(main())
    print("Disabled until we check that the nightly-branch-monitor.yml automation works")