#!/usr/bin/env bash

set -e

CMD=$*

if [ -z "$CMD" ]
then
    CMD=bash
fi

# retry docker pull if fails
for i in {1..3}; do docker-compose pull -q testrunner && break || sleep 3; done

# install and upgrade tox and riot in case testrunner image has not been updated
# DEV: Use `--no-TTY` when running in CircleCI
NO_TTY=$([[ "${CIRCLECI}" = "true" ]] && echo "--no-TTY")
docker-compose run -e CIRCLE_NODE_TOTAL -e CIRCLE_NODE_INDEX -e DD_TRACE_AGENT_URL "${NO_TTY}" --quiet-pull --rm testrunner bash -c "pip install -q --disable-pip-version-check riot tox && $CMD"
