#!/usr/bin/env bash
set -ex

if [ $# != 1 ]; then
    echo "Usage: scripts/perf-build-push <repository>"
    exit 1
fi

REPOSITORY="$1"
shift

for SCENARIO in "encoder" "span" "tracer" "django_simple";
do
    TAG="${REPOSITORY}/perf-${SCENARIO}"
    docker build -q -t "${TAG}" --build-arg SCENARIO="${SCENARIO}" -f benchmarks/base/Dockerfile benchmarks/
    docker push -q "${TAG}:latest"
done
