#!/usr/bin/env bash
set -e


if [ $# != 2 ]; then
    echo "Usage: perf-build-scenario <scenario> <imagetag>"
    exit 1
fi

SCENARIO="$1"
shift
TAG="$1"
shift

BUILD_ARGS=()
if [[ -n "${PYTHON_VERSION:-}" ]]; then
    BUILD_ARGS+=(--build-arg "PYTHON_VERSION=${PYTHON_VERSION}")
fi

docker build -t "${TAG}" "${BUILD_ARGS[@]}" --build-arg SCENARIO="${SCENARIO}" benchmarks/
