#!/bin/bash

PATTERN=${1}
COVERAGE=${2:-false}

commit_file="latest-success-commit"

if [[ -f "$commit_file" ]]; then
    echo "Commit file found"
    latest_success_commit=$(cat $commit_file)
    does_not_need_run=$(./scripts/needs_testrun.py $SUITE --sha $latest_success_commit)
    if [[ $does_not_need_run ]]; then
        echo "No relevant changes since last successful run"
        exit 0
    fi
fi

hashes=$(riot list --hash-only $PATTERN | sort | circleci tests split)

all_passed=0
for hash in $hashes; do
    echo "Running tests for $hash"
    ./scripts/ddtest riot -v run --exitfirst --pass-env -s $hash $([ -v _CI_DD_API_KEY ] && echo '--ddtrace') $([[ "$COVERAGE" == false ]] && echo '--no-cov')
    [[ $? ]] && break
    all_passed=1
done

[[ $all_passed ]] && echo $CIRCLE_SHA1 > $commit_file

./scripts/check-diff \
    ".riot/requirements/" \
    "Changes detected after running riot. Consider deleting changed files, \
    running scripts/compile-and-prune-test-requirements and committing the result."
