import Any
from ddtrace.internal import periodic, service

class CollectorError(Exception): ...
class CollectorUnavailable(CollectorError): ...

class Collector(service.Service):
    recorder: Any = ...
    @staticmethod
    def snapshot() -> None: ...

class PeriodicCollector(Collector, periodic.PeriodicService):
    def periodic(self) -> None: ...
    @staticmethod
    def collect() -> None: ...

class CaptureSampler:
    capture_pct: Any = ...
    def capture_pct_validator(self, attribute: Any, value: Any) -> None: ...
    def capture(self): ...

class CaptureSamplerCollector(Collector):
    capture_pct: Any = ...
