from ddtrace.profiling import collector, event
from typing import Any

class MemoryAllocSampleEvent(event.StackBasedEvent):
    size: Any = ...
    capture_pct: Any = ...
    nevents: Any = ...

class MemoryHeapSampleEvent(event.StackBasedEvent):
    size: Any = ...
    sample_size: Any = ...

class MemoryCollector(collector.PeriodicCollector):
    max_nframe: Any = ...
    heap_sample_size: Any = ...
    ignore_profiler: Any = ...
    def stop(self) -> None: ...
    def snapshot(self): ...
    def collect(self): ...
