# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.internal.cassandra.patch import patch
from ddtrace.contrib.internal.cassandra.session import get_version


try:
    from ddtrace.contrib.internal.cassandra.patch import unpatch
except ImportError:
    unpatch = None
from tests.contrib.patch import PatchTestCase


class TestCassandraPatch(PatchTestCase.Base):
    __integration_name__ = "cassandra"
    __module_name__ = "cassandra.cluster"
    __patch_func__ = patch
    __unpatch_func__ = unpatch
    __get_version__ = get_version

    def assert_module_patched(self, cassandra_cluster):
        pass

    def assert_not_module_patched(self, cassandra_cluster):
        pass

    def assert_not_module_double_patched(self, cassandra_cluster):
        pass
