from typing import Any

MOLTEN_VERSION: Any

def patch() -> None: ...
def unpatch() -> None: ...
def patch_app_call(wrapped: Any, instance: Any, args: Any, kwargs: Any): ...
def patch_app_init(wrapped: Any, instance: Any, args: Any, kwargs: Any) -> None: ...
