from ddtrace.vendor import wrapt
from typing import Any

MOLTEN_ROUTE: str

def trace_wrapped(resource: Any, wrapped: Any, *args: Any, **kwargs: Any): ...
def trace_func(resource: Any): ...

class WrapperComponent(wrapt.ObjectProxy):
    def can_handle_parameter(self, *args: Any, **kwargs: Any): ...

class WrapperRenderer(wrapt.ObjectProxy):
    def render(self, *args: Any, **kwargs: Any): ...

class WrapperMiddleware(wrapt.ObjectProxy):
    def __call__(self, *args: Any, **kwargs: Any): ...

class WrapperRouter(wrapt.ObjectProxy):
    def match(self, *args: Any, **kwargs: Any): ...
