from typing import Union

StringType = Union[str, bytes, None]

def set_crashtracker_stdout_filename(filename: StringType) -> None: ...
def set_crashtracker_stderr_filename(filename: StringType) -> None: ...
def set_crashtracker_alt_stack(alt_stack: bool) -> None: ...
def set_crashtracker_resolve_frames_disable() -> None: ...
def set_crashtracker_resolve_frames_fast() -> None: ...
def set_crashtracker_resolve_frames_full() -> None: ...
def start_crashtracker() -> None: ...
