from typing import Union

StringType = Union[str, bytes, None]

def set_url(url: StringType) -> None: ...
def set_service(service: StringType) -> None: ...
def set_env(env: StringType) -> None: ...
def set_version(version: StringType) -> None: ...
def set_runtime(runtime: StringType) -> None: ...
def set_runtime_version(runtime_version: StringType) -> None: ...
def set_library_version(profiler_version: StringType) -> None: ...
def set_stdout_filename(filename: StringType) -> None: ...
def set_stderr_filename(filename: StringType) -> None: ...
def set_alt_stack(alt_stack: bool) -> None: ...
def set_resolve_frames_disable() -> None: ...
def set_resolve_frames_fast() -> None: ...
def set_resolve_frames_full() -> None: ...
def set_receiver_binary_path(StringType path) -> bool: ...
def start() -> None: ...
