from typing import Any
from typing import List
from typing import Optional
from typing import Union

from ddtrace.span import Span

Trace = List[Span]

class BufferFull(Exception):
    pass

class BufferItemTooLarge(Exception):
    pass

class BufferedEncoder(object):
    content_type: str
    def encode_item(self, item: Any) -> bytes: ...
    def encode(self) -> Optional[bytes]: ...

class ListBufferedEncoder(ListBufferedEncoder):
    def __init__(self, max_size: int, max_item_size: int) -> None: ...
    def __len__(self) -> int: ...
    def clear(self) -> None: ...
    def put(self, item: Any) -> None: ...
    def get(self) -> List[bytes]: ...
    @property
    def size(self) -> int: ...
    @property
    def max_size(self) -> int: ...
    @property
    def max_item_size(self) -> int: ...

class MsgpackEncoder(ListBufferedEncoder):
    def _decode(self, data: Union[str, bytes]) -> Any: ...
