from typing import Dict

class TagsetDecodeError(ValueError): ...
class TagsetEncodeError(ValueError): ...

class TagsetMaxSizeError(TagsetEncodeError):
    values: Dict[str, str]
    max_size: int
    current_results: str
    def __init__(self, values: Dict[str, str], max_size: int, current_results: str): ...

def decode_tagset_string(tagset: str) -> Dict[str, str]: ...
def encode_tagset_values(values: Dict[str, str], max_size: int = 512) -> str: ...
