class TagsetDecodeError(ValueError): ...
class TagsetEncodeError(ValueError): ...

class TagsetMaxSizeEncodeError(TagsetEncodeError):
    values: dict[str, str]
    max_size: int
    current_results: str
    def __init__(self, values: dict[str, str], max_size: int, current_results: str): ...

class TagsetMaxSizeDecodeError(TagsetDecodeError):
    value: dict[str, str]
    max_size: int
    def __init__(self, value: dict[str, str], max_size: int): ...

def decode_tagset_string(tagset: str) -> dict[str, str]: ...
def encode_tagset_values(values: dict[str, str], max_size: int = 512) -> str: ...
