PROPAGATION_STYLE_DATADOG = "datadog"
PROPAGATION_STYLE_B3 = "b3"
PROPAGATION_STYLE_B3_SINGLE_HEADER = "b3 single header"
PROPAGATION_STYLE_ALL = (PROPAGATION_STYLE_DATADOG, PROPAGATION_STYLE_B3, PROPAGATION_STYLE_B3_SINGLE_HEADER)

_TRACESTATE_KEY = "tracestate"
_TRACEPARENT_KEY = "traceparent"

DEFAULT_SERVICE_NAME = "unnamed_python_service"
