from typing import Any, Optional, Protocol

class Metrics(Protocol):
    ddwaf_version: str
    _set_waf_error_log: Any
    _set_waf_request_metrics: Any

def _set_waf_updates_metric(info: Any, success: bool) -> None: ...
def _set_waf_init_metric(info: Any, success: bool) -> None: ...
def _report_waf_truncations(observator: Any) -> None: ...
def _report_waf_run_error(error: int, rule_version: str, rule_type: Optional[str]) -> None: ...
def _set_waf_request_metrics(*args: Any) -> None: ...
def _report_api_security(route: bool, schemas: int) -> None: ...
def _report_rasp_skipped(rule_type: str, import_error: bool) -> None: ... 