from distutils.dep_util import newer_group
from itertools import chain
import os
from pathlib import Path
import platform
import re
import shutil
import subprocess
import sys
import sysconfig
import typing as t

import cmake
from setuptools import Extension
from setuptools.command.build_ext import build_ext


try:
    # ORDER MATTERS
    # Import this after setuptools or it will fail
    from Cython.Build import cythonize
    import Cython.Distutils
except ImportError:
    raise ImportError(
        "Failed to import Cython modules. This can happen under versions of pip older than 18 that don't "
        "support installing build requirements during setup. If you're using pip, make sure it's a "
        "version >=18.\nSee the quickstart documentation for more information:\n"
        "https://ddtrace.readthedocs.io/en/stable/installation_quickstart.html"
    )

import hashlib

import _build.constants as _c
from _build.constants import BUILD_PROFILING_NATIVE_TESTS
from _build.constants import CARGO_TARGET_DIR
from _build.constants import COMPILE_MODE
from _build.constants import CURRENT_OS
from _build.constants import DDUP_DIR
from _build.constants import FAST_BUILD
from _build.constants import HERE
from _build.constants import IAST_DIR
from _build.constants import IS_PYSTON
from _build.constants import NATIVE_CRATE
from _build.constants import STACK_DIR
from _build.download import LibraryDownload
from _build.rust import CustomBuildRust
from _build.rust import RustExtension
from _build.rust import rust_features
from _build.utils import is_64_bit_python


class ExtensionHashes(build_ext):
    def run(self):
        try:
            dist = self.distribution
            for ext in chain(dist.ext_modules, getattr(dist, "rust_extensions", [])):
                if isinstance(ext, CMakeExtension):
                    sources = ext.get_sources(self)
                elif isinstance(ext, RustExtension):
                    source_path = Path(ext.path).parent
                    sources = [
                        _
                        for _ in source_path.glob("**/*")
                        if _.is_file()
                        and _.relative_to(source_path).parts[0]
                        != f"target{sys.version_info.major}.{sys.version_info.minor}"
                    ]
                else:
                    sources = [Path(_) for _ in ext.sources]

                sources_hash = hashlib.sha256()
                # DEV: Make sure to include the rust features since changing them changes what gets built
                for feature in rust_features:
                    sources_hash.update(feature.encode())
                for source in sorted(sources):
                    sources_hash.update(source.read_bytes())
                hash_digest = sources_hash.hexdigest()

                entries: list[tuple[str, str, str]] = []
                entries.append((ext.name, hash_digest, str(Path(self.get_ext_fullpath(ext.name)))))

                # For profiling, these headers are generated by the Rust extension
                # and they are used to build dd_wrapper shared library. We need
                # to persist in the extension hash cache so that we can handle
                # the case where Rust extension is not rebuilt but the dd_wrapper
                # needs to be rebuilt when its sources changed.
                if isinstance(ext, RustExtension) and "profiling" in ext.features:
                    for f in ["common.h", "profiling.h"]:
                        entries.append(
                            (
                                ext.name,
                                hash_digest,
                                str(CARGO_TARGET_DIR / "include" / "datadog" / f),
                            )
                        )

                # Include any dependencies that might have been built alongside
                # the extension.
                if isinstance(ext, CMakeExtension):
                    entries.extend(
                        (f"{ext.name}-{dependency.name}", hash_digest, str(dependency) + "*")
                        for dependency in ext.dependencies
                    )

                for entry in entries:
                    print("#EXTHASH:", entry)

        except Exception as e:
            print("WARNING: Failed to compute extension hashes: %s" % e)
            raise e


class CMakeExtension(Extension):
    def __init__(
        self,
        name,
        source_dir=Path.cwd(),
        extra_source_dirs=[],
        cmake_args=[],
        build_args=[],
        install_args=[],
        build_type=None,
        optional=True,  # By default, extensions are optional
        dependencies=[],
    ):
        super().__init__(name, sources=[])
        self.source_dir = source_dir
        self.extra_source_dirs = extra_source_dirs  # extra source dirs to include when computing extension hash
        self.cmake_args = cmake_args or []
        self.build_args = build_args or []
        self.install_args = install_args or []
        self.build_type = build_type or COMPILE_MODE
        self.optional = optional  # If True, cmake errors are ignored
        self.dependencies = dependencies

    def get_sources(self, cmd: build_ext) -> list:
        """
        Returns the list of source files for this extension.
        This is used by the CustomBuildExt class to determine if the extension needs to be rebuilt.
        """
        full_path = Path(cmd.get_ext_fullpath(self.name))

        # Collect all the source files within the source directory. We exclude
        # Python sources and anything that does not have a suffix (most likely
        # a binary file), or that has the same name as the extension binary.
        def is_valid_source(src: Path) -> bool:
            return (
                src.is_file()
                and src.name != full_path.name
                and src.suffix
                and src.suffix not in {".py", ".pyc", ".pyi"}
            )

        return [
            src
            for source_dir in chain([self.source_dir], self.extra_source_dirs)
            for src in Path(source_dir).glob("**/*")
            if is_valid_source(src)
        ]


class CustomBuildExt(build_ext):
    INCREMENTAL = os.getenv("DD_CMAKE_INCREMENTAL_BUILD", "1").lower() in ("1", "yes", "on", "true")

    def run(self):
        self.build_rust()

        # Build libdd_wrapper before building other extensions that depend on it
        if CURRENT_OS in ("Linux", "Darwin") and is_64_bit_python():
            self.build_libdd_wrapper()

        super().run()
        for ext in self.extensions:
            self.build_extension(ext)

    def build_rust(self):
        """Build the Rust component using CustomBuildRust command."""
        self.suffix = sysconfig.get_config_var("EXT_SUFFIX")
        native_name = f"_native{self.suffix}"

        if _c.IS_EDITABLE or getattr(self, "inplace", False):
            self.output_dir = HERE / "ddtrace" / "internal" / "native"
        else:
            self.output_dir = HERE / Path(self.build_lib) / "ddtrace" / "internal" / "native"

        library = self.output_dir / native_name

        # Determine the Rust source binary path - need to handle different architectures
        rust_source = NATIVE_CRATE / "target" / "release" / f"lib_native{self.suffix}"
        if not rust_source.exists():
            # Fallback to generic .so extension for cross-platform compatibility
            rust_source = NATIVE_CRATE / "target" / "release" / "lib_native.so"

        # Check if we need to run the Rust build by checking if sources are newer than the destination
        should_build = True
        if library.exists():
            library_mtime = library.stat().st_mtime

            # Check if any Rust source files are newer than the destination library
            cargo_files = [NATIVE_CRATE / "Cargo.toml", NATIVE_CRATE / "Cargo.lock"]

            # Get all source files (including subdirectories)
            source_files = []
            # Find all .rs files in the crate (including subdirectories)
            source_files.extend(NATIVE_CRATE.glob("**/*.rs"))
            # Add cargo files
            source_files.extend([f for f in cargo_files if f.exists()])

            # Check if any source file is newer than the library
            newest_source_time = 0
            for src_file in source_files:
                if src_file.exists():
                    newest_source_time = max(newest_source_time, src_file.stat().st_mtime)

            required_headers = ["common.h"]
            if "profiling" in rust_features:
                required_headers.append("profiling.h")

            include_dir = CARGO_TARGET_DIR / "include" / "datadog"
            headers_exist = include_dir.exists() and all((include_dir / header).exists() for header in required_headers)

            # Only rebuild if source files are newer than the destination OR if any required header is missing
            should_build = newest_source_time > library_mtime or not headers_exist

        if should_build:
            # Create and run the CustomBuildRust command
            build_rust_cmd = CustomBuildRust(self.distribution)
            build_rust_cmd.initialize_options()
            build_rust_cmd.finalize_options()
            # Propagate the inplace flag to the rust build command
            build_rust_cmd.inplace = getattr(self, "inplace", False)
            build_rust_cmd.run()

            if not library.exists():
                raise RuntimeError("Not able to find native library")

            print(f"Built and copied Rust extension: {native_name}")
            self.built_native = True
        else:
            print(f"Skipping Rust extension build (no changes): {native_name}")
            self.built_native = False

        # Set SONAME (always do this as it's idempotent)
        if CURRENT_OS == "Linux":
            subprocess.run(["patchelf", "--set-soname", native_name, library], check=True)
        elif CURRENT_OS == "Darwin":
            subprocess.run(["install_name_tool", "-id", native_name, library], check=True)

    def build_libdd_wrapper(self):
        """Build libdd_wrapper shared library as a dependency for profiling extensions."""
        dd_wrapper_dir = DDUP_DIR.parent / "dd_wrapper"

        # Determine output directory (profiling directory).
        # Store as self.wrapper_output_dir so _get_common_cmake_args can pass
        # DD_WRAPPER_DIR to downstream extensions (ddup, stack, memalloc).
        if _c.IS_EDITABLE or getattr(self, "inplace", False):
            wrapper_output_dir = HERE / "ddtrace" / "internal" / "datadog" / "profiling"
        else:
            wrapper_output_dir = HERE / Path(self.build_lib) / "ddtrace" / "internal" / "datadog" / "profiling"
        self.wrapper_output_dir = wrapper_output_dir

        wrapper_name = f"libdd_wrapper{self.suffix}"
        wrapper_library = wrapper_output_dir / wrapper_name

        # Check if we need to build libdd_wrapper by checking if sources are newer
        should_build = True
        if wrapper_library.exists():
            wrapper_mtime = wrapper_library.stat().st_mtime

            # Check dd_wrapper source files
            source_files = []
            source_files.extend(dd_wrapper_dir.glob("**/*.cpp"))
            source_files.extend(dd_wrapper_dir.glob("**/*.hpp"))
            source_files.extend([dd_wrapper_dir / "CMakeLists.txt"])

            # Check if any source file is newer than the wrapper library
            newest_source_time = 0
            for src_file in source_files:
                if src_file.exists():
                    newest_source_time = max(newest_source_time, src_file.stat().st_mtime)

            # Rebuild if source files changed OR if _native.so was rebuilt (our dependency)
            source_files_changed = newest_source_time > wrapper_mtime
            print(f"source_files_changed: {source_files_changed}")
            print(f"built_native: {getattr(self, 'built_native', False)}")
            should_build = source_files_changed or getattr(self, "built_native", False)

        if should_build:
            # Build libdd_wrapper using CMake
            cmake_build_dir = Path(self.build_lib.replace("lib.", "cmake."), "libdd_wrapper_build").resolve()
            cmake_build_dir.mkdir(parents=True, exist_ok=True)

            cmake_args = self._get_common_cmake_args(dd_wrapper_dir, cmake_build_dir, wrapper_output_dir, wrapper_name)

            build_args = [f"--config {COMPILE_MODE}"]
            if "CMAKE_BUILD_PARALLEL_LEVEL" not in os.environ:
                if hasattr(self, "parallel") and self.parallel:
                    build_args += [f"-j{self.parallel}"]

            install_args = [f"--config {COMPILE_MODE}"]

            cmake_command = (Path(cmake.CMAKE_BIN_DIR) / "cmake").resolve()
            subprocess.run([cmake_command, *cmake_args], cwd=cmake_build_dir, check=True)
            subprocess.run([cmake_command, "--build", ".", *build_args], cwd=cmake_build_dir, check=True)
            subprocess.run([cmake_command, "--install", ".", *install_args], cwd=cmake_build_dir, check=True)

            print(f"Built libdd_wrapper shared library: {wrapper_name}")
        else:
            print(f"Skipping libdd_wrapper build (no changes): {wrapper_name}")

    @staticmethod
    def try_strip_symbols(so_file):
        if CURRENT_OS == "Linux" and shutil.which("strip") is not None:
            try:
                subprocess.run(["strip", "-g", so_file], check=True)
            except subprocess.CalledProcessError as e:
                print(
                    "WARNING: stripping '{}' returned non-zero exit status ({}), ignoring".format(so_file, e.returncode)
                )
            except Exception as e:
                print(
                    "WARNING: An error occurred while stripping the symbols from '{}', ignoring: {}".format(so_file, e)
                )

    def build_extension(self, ext):
        if isinstance(ext, CMakeExtension):
            try:
                self.build_extension_cmake(ext)
            except subprocess.CalledProcessError as e:
                print("WARNING: Command '{}' returned non-zero exit status {}.".format(e.cmd, e.returncode))
                if ext.optional:
                    return
                raise
            except Exception as e:
                print("WARNING: An error occurred while building the CMake extension {}, {}.".format(ext.name, e))
                if ext.optional:
                    return
                raise
        else:
            super().build_extension(ext)

        if COMPILE_MODE.lower() in ("release", "minsizerel"):
            try:
                self.try_strip_symbols(self.get_ext_fullpath(ext.name))
            except Exception as e:
                print(f"WARNING: An error occurred while building the extension: {e}")

    def _get_common_cmake_args(self, source_dir, build_dir, output_dir, extension_name, build_type=None):
        """Get common CMake arguments used by both libdd_wrapper and extensions."""
        # Use base_prefix (not prefix) to get the actual Python installation path even when in a venv
        # Resolve symlinks so CMake can find include/lib directories relative to the real installation
        python_root = Path(sys.base_prefix).resolve()

        cmake_args = [
            f"-S{source_dir}",
            f"-B{build_dir}",
            f"-DPython3_ROOT_DIR={python_root}",
            f"-DPython3_EXECUTABLE={sys.executable}",
            f"-DPYTHON_EXECUTABLE={sys.executable}",
            f"-DCMAKE_BUILD_TYPE={build_type or COMPILE_MODE}",
            f"-DLIB_INSTALL_DIR={output_dir}",
            f"-DEXTENSION_NAME={extension_name}",
            f"-DEXTENSION_SUFFIX={self.suffix}",
            f"-DNATIVE_EXTENSION_LOCATION={self.output_dir}",
            f"-DRUST_GENERATED_HEADERS_DIR={CARGO_TARGET_DIR / 'include'}",
        ]
        # Pass DD_WRAPPER_DIR for ddup/stack/memalloc cmake builds to find libdd_wrapper
        if hasattr(self, "wrapper_output_dir"):
            cmake_args += [
                f"-DDD_WRAPPER_DIR={self.wrapper_output_dir}",
            ]

        # Point FetchContent downloads at the persistent download cache so CMake
        # doesn't re-fetch from GitHub (e.g. abseil) on every build invocation.
        # The cache dir is shared with other downloaded build dependencies and is
        # preserved between CI runs. FETCHCONTENT_BASE_DIR defaults to a path
        # inside the ephemeral cmake build dir, so without this every build would
        # re-download from GitHub.
        cmake_args += [
            f"-DFETCHCONTENT_BASE_DIR={LibraryDownload.CACHE_DIR / '_cmake_deps'}",
        ]

        # Add sccache support if available
        sccache_path = os.getenv("DD_SCCACHE_PATH")
        if sccache_path:
            cmake_args += [
                f"-DCMAKE_C_COMPILER={os.getenv('DD_CC_OLD', shutil.which('cc'))}",
                f"-DCMAKE_C_COMPILER_LAUNCHER={sccache_path}",
                f"-DCMAKE_CXX_COMPILER={os.getenv('DD_CXX_OLD', shutil.which('c++'))}",
                f"-DCMAKE_CXX_COMPILER_LAUNCHER={sccache_path}",
            ]

        return cmake_args

    def build_extension_cmake(self, ext: "CMakeExtension") -> None:
        if _c.IS_EDITABLE and self.INCREMENTAL:
            # DEV: Rudimentary incremental build support. We copy the logic from
            # setuptools' build_ext command, best effort.
            full_path = Path(self.get_ext_fullpath(ext.name))
            ext_path = Path(ext.source_dir, full_path.name)

            force = self.force

            if ext.dependencies:
                dependencies = [
                    str(d.resolve())
                    for dependency in ext.dependencies
                    for d in dependency.parent.glob(dependency.name + "*")
                    if d.is_file()
                ]
                if not dependencies:
                    # We expected some dependencies but none were found so we
                    # force the build to happen
                    force = True

            else:
                dependencies = []

            if not (
                force
                or newer_group(
                    [str(_.resolve()) for _ in ext.get_sources(self)] + dependencies, str(ext_path.resolve()), "newer"
                )
            ):
                print(f"skipping '{ext.name}' CMake extension (up-to-date)")

                # We need to copy the binary where setuptools expects it
                full_path.parent.mkdir(parents=True, exist_ok=True)
                if ext_path.resolve() != full_path.resolve():
                    shutil.copy(ext_path, full_path)

                return
            else:
                print(f"building '{ext.name}' CMake extension")

        # Define the build and output directories
        output_dir = Path(self.get_ext_fullpath(ext.name)).parent.resolve()
        extension_basename = Path(self.get_ext_fullpath(ext.name)).name

        # We derive the cmake build directory from the output directory, but put it in
        # a sibling directory to avoid polluting the final package
        cmake_build_dir = Path(self.build_lib.replace("lib.", "cmake."), ext.name).resolve()
        cmake_build_dir.mkdir(parents=True, exist_ok=True)

        # Which commands are passed to _every_ cmake invocation
        cmake_args = ext.cmake_args or []
        cmake_args += self._get_common_cmake_args(
            ext.source_dir, cmake_build_dir, output_dir, extension_basename, ext.build_type
        )

        if BUILD_PROFILING_NATIVE_TESTS:
            cmake_args += ["-DBUILD_TESTING=ON"]
        else:
            cmake_args += ["-DBUILD_TESTING=OFF"]

        # If this is an inplace build, propagate this fact to CMake in case it's helpful
        # In particular, this is needed for build products which are not otherwise managed
        # by setuptools/distutils
        if _c.IS_EDITABLE:
            # the INPLACE_LIB_INSTALL_DIR should be the source dir of the extension
            cmake_args.append("-DINPLACE_LIB_INSTALL_DIR={}".format(ext.source_dir))

        # Arguments to the cmake --build command
        build_args = ext.build_args or []
        build_args += ["--config {}".format(ext.build_type)]
        if "CMAKE_BUILD_PARALLEL_LEVEL" not in os.environ:
            # CMAKE_BUILD_PARALLEL_LEVEL works across all generators
            # self.parallel is a Python 3 only way to set parallel jobs by hand
            # using -j in the build_ext call, not supported by pip or PyPA-build.
            # DEV: -j is supported in CMake 3.12+ only.
            if hasattr(self, "parallel") and self.parallel:
                build_args += ["-j{}".format(self.parallel)]

        # Arguments to cmake --install command
        install_args = ext.install_args or []
        install_args += ["--config {}".format(ext.build_type)]

        # platform/version-specific arguments--may go into cmake, build, or install as needed
        if CURRENT_OS == "Windows":
            arch = platform.machine().lower()
            if arch in ("amd64", "x86_64"):
                cmake_arch = "x64"
            elif arch in ("x86", "i386", "i686"):
                cmake_arch = "Win32"
            elif arch == "arm64":
                cmake_arch = "ARM64"
            else:
                raise RuntimeError(f"Unsupported architecture: {arch}")
            cmake_args += [f"-A{cmake_arch}"]
        if CURRENT_OS == "Darwin":
            # Cross-compile support for macOS - respect ARCHFLAGS if set
            # Darwin Universal2 should bundle both architectures
            # This is currently specific to IAST and requires cmakefile support
            archs = re.findall(r"-arch (\S+)", os.environ.get("ARCHFLAGS", ""))
            if archs:
                cmake_args += [
                    "-DBUILD_MACOS=ON",
                    "-DCMAKE_OSX_ARCHITECTURES={}".format(";".join(archs)),
                    # Set macOS SDK default deployment target to 10.14 for C++17 support (if unset, may default to 10.9)
                    "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.14",
                ]

        if CURRENT_OS != "Windows" and FAST_BUILD and ext.build_type:
            cmake_args += [
                "-DCMAKE_C_FLAGS_%s=-O0" % ext.build_type.upper(),
                "-DCMAKE_CXX_FLAGS_%s=-O0" % ext.build_type.upper(),
            ]
        cmake_command = (
            Path(cmake.CMAKE_BIN_DIR) / "cmake"
        ).resolve()  # explicitly use the cmake provided by the cmake package
        subprocess.run([cmake_command, *cmake_args], cwd=cmake_build_dir, check=True)
        subprocess.run([cmake_command, "--build", ".", *build_args], cwd=cmake_build_dir, check=True)
        subprocess.run([cmake_command, "--install", ".", *install_args], cwd=cmake_build_dir, check=True)


def get_ext_modules():
    if CURRENT_OS == "Windows":
        extra_compile_args = []
        debug_compile_args = []
        fast_build_args = []
    else:
        linux = CURRENT_OS == "Linux"
        extra_compile_args = ["-DPy_BUILD_CORE"]
        fast_build_args = ["-O0"] if FAST_BUILD else []
        if COMPILE_MODE.lower() == "debug":
            if linux:
                debug_compile_args = ["-g", "-O0", "-Wall", "-Wextra", "-Wpedantic"]
            else:
                debug_compile_args = [
                    "-g",
                    "-O0",
                    "-Wall",
                    "-Wextra",
                    "-Wpedantic",
                    # Cython is not deprecation-proof
                    "-Wno-deprecated-declarations",
                ]
        else:
            debug_compile_args = []

    if not IS_PYSTON:
        ext_modules: list[t.Union[Extension, Cython.Distutils.Extension, RustExtension]] = [
            Extension(
                "ddtrace.internal._threads",
                sources=["ddtrace/internal/_threads.cpp"],
                extra_compile_args=(
                    ["-std=c++20", "-Wall", "-Wextra"] + fast_build_args
                    if CURRENT_OS != "Windows"
                    else ["/std:c++20", "/MT"]
                ),
            ),
        ]

        if platform.system() not in ("Windows", ""):
            ext_modules.append(
                Extension(
                    "ddtrace.appsec._iast._stacktrace",
                    sources=[
                        "ddtrace/appsec/_iast/_stacktrace.c",
                    ],
                    extra_compile_args=extra_compile_args + debug_compile_args + fast_build_args,
                )
            )
            ext_modules.append(
                Extension(
                    "ddtrace.appsec._iast._ast.iastpatch",
                    sources=[
                        "ddtrace/appsec/_iast/_ast/iastpatch.c",
                    ],
                    extra_compile_args=extra_compile_args + debug_compile_args + fast_build_args,
                )
            )
            ext_modules.append(
                CMakeExtension("ddtrace.appsec._iast._taint_tracking._native", source_dir=IAST_DIR, optional=False)
            )

        if CURRENT_OS in ("Linux", "Darwin") and is_64_bit_python():
            # Memory profiler now uses CMake to support Abseil dependency
            MEMALLOC_DIR = HERE / "ddtrace" / "profiling" / "collector"
            memalloc_cmake_args = []
            if os.environ.get("DD_PROFILING_MEMALLOC_ASSERT_ON_REENTRY", "0") not in ("0", ""):
                memalloc_cmake_args.append("-DMEMALLOC_ASSERT_ON_REENTRY=ON")
            ext_modules.append(
                CMakeExtension(
                    "ddtrace.profiling.collector._memalloc",
                    source_dir=MEMALLOC_DIR,
                    cmake_args=memalloc_cmake_args,
                    optional=False,
                )
            )

            ext_modules.append(
                CMakeExtension(
                    "ddtrace.internal.datadog.profiling.ddup._ddup",
                    source_dir=DDUP_DIR,
                    extra_source_dirs=[
                        DDUP_DIR / ".." / "cmake",
                        DDUP_DIR / ".." / "dd_wrapper",
                    ],
                    optional=False,
                )
            )

            ext_modules.append(
                CMakeExtension(
                    "ddtrace.internal.datadog.profiling.stack._stack",
                    source_dir=STACK_DIR,
                    extra_source_dirs=[
                        STACK_DIR / ".." / "cmake",
                        STACK_DIR / ".." / "dd_wrapper",
                    ],
                    optional=False,
                ),
            )

    else:
        ext_modules = []

    return ext_modules


def get_cython_exts():
    if CURRENT_OS == "Windows":
        encoding_libraries = ["ws2_32"]
    else:
        encoding_libraries = []

    cython_exts = []
    if os.getenv("DD_CYTHONIZE", "1").lower() in ("1", "yes", "on", "true"):
        cython_exts = cythonize(
            [
                Cython.Distutils.Extension(
                    "ddtrace.internal._tagset",
                    sources=["ddtrace/internal/_tagset.pyx"],
                    language="c",
                ),
                Extension(
                    "ddtrace.internal._encoding",
                    ["ddtrace/internal/_encoding.pyx"],
                    include_dirs=["."],
                    libraries=encoding_libraries,
                    define_macros=[(f"__{sys.byteorder.upper()}_ENDIAN__", "1")],
                ),
                Extension(
                    "ddtrace.internal.telemetry.metrics_namespaces",
                    ["ddtrace/internal/telemetry/metrics_namespaces.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling._threading",
                    sources=["ddtrace/profiling/_threading.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling.collector._task",
                    sources=["ddtrace/profiling/collector/_task.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling.collector._exception",
                    sources=["ddtrace/profiling/collector/_exception.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling.collector._fast_poisson",
                    sources=["ddtrace/profiling/collector/_fast_poisson.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling.collector._sampler",
                    sources=["ddtrace/profiling/collector/_sampler.pyx"],
                    language="c",
                ),
                Cython.Distutils.Extension(
                    "ddtrace.profiling.collector._lock",
                    sources=["ddtrace/profiling/collector/_lock.pyx"],
                    language="c",
                ),
            ],
            compile_time_env={
                "PY_MAJOR_VERSION": sys.version_info.major,
                "PY_MINOR_VERSION": sys.version_info.minor,
                "PY_MICRO_VERSION": sys.version_info.micro,
                "PY_VERSION_HEX": sys.hexversion,
            },
            force=os.getenv("DD_SETUP_FORCE_CYTHONIZE", "0") == "1",
            annotate=os.getenv("_DD_CYTHON_ANNOTATE") == "1",
            compiler_directives={"language_level": "3"},
            cache=True,
        )
    return cython_exts
