from opentracing import Span as OpenTracingSpan
from typing import Any, Optional

class Span(OpenTracingSpan):
    finished: bool = ...
    def __init__(self, tracer: Any, context: Any, operation_name: Any) -> None: ...
    def finish(self, finish_time: Optional[Any] = ...) -> None: ...
    def set_baggage_item(self, key: Any, value: Any): ...
    def get_baggage_item(self, key: Any): ...
    def set_operation_name(self, operation_name: Any) -> None: ...
    def log_kv(self, key_values: Any, timestamp: Optional[Any] = ...): ...
    def set_tag(self, key: Any, value: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
