import Any
from opentracing import SpanContext as OpenTracingSpanContext
from typing import Optional

class SpanContext(OpenTracingSpanContext):
    def __init__(self, trace_id: Optional[Any] = ..., span_id: Optional[Any] = ..., sampling_priority: Optional[Any] = ..., baggage: Optional[Any] = ..., ddcontext: Optional[Any] = ...) -> None: ...
    @property
    def baggage(self) -> Any: ...
    def set_baggage_item(self, key: Any, value: Any) -> None: ...
    def with_baggage_item(self, key: Any, value: Any): ...
    def get_baggage_item(self, key: Any): ...
