services:
  redis:
    image: redis:7-alpine
    networks:
      - my_network

  producer:
    build:
      context: ./
      dockerfile: Dockerfile.producer
    container_name: celery-producer
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - datadog-agent
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_STARTUP_LOGS=true
      - DD_TRACE_DEBUG=true
      - DD_CELERY_DISTRIBUTED_TRACING=true
      - DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED=false
    networks:
      - my_network

  consumer:
    build:
      context: ./
      dockerfile: Dockerfile.consumer
    container_name: celery-consumer
    depends_on:
      - redis
      - datadog-agent
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_STARTUP_LOGS=true
      - DD_TRACE_DEBUG=true
      - DD_CELERY_DISTRIBUTED_TRACING=true
      - DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED=false
    networks:
      - my_network

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    environment:
      - DD_API_KEY=XXXXXXXXXXXXXXXXXXXX
      - DD_SITE=datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_network
