# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.
from ddtrace.contrib.internal.pymongo.patch import get_version
from ddtrace.contrib.internal.pymongo.patch import patch
from ddtrace.contrib.internal.pymongo.patch import pymongo
from ddtrace.contrib.internal.pymongo.patch import unpatch
from tests.contrib.patch import PatchTestCase


_VERSION = pymongo.version_tuple

if _VERSION >= (4, 9):
    from pymongo.synchronous.pool import Connection
    from pymongo.synchronous.server import Server
    from pymongo.synchronous.topology import Topology
elif _VERSION >= (4, 5):
    from pymongo.pool import Connection
    from pymongo.server import Server
    from pymongo.topology import Topology
else:
    from pymongo.pool import SocketInfo as Connection
    from pymongo.server import Server
    from pymongo.topology import Topology

# Import async classes if available (pymongo >= 4.12)
if _VERSION >= (4, 12):
    from pymongo.asynchronous.mongo_client import AsyncMongoClient
    from pymongo.asynchronous.pool import AsyncConnection
    from pymongo.asynchronous.server import Server as AsyncServer
    from pymongo.asynchronous.topology import Topology as AsyncTopology


class TestPymongoPatch(PatchTestCase.Base):
    __integration_name__ = "pymongo"
    __module_name__ = "pymongo"
    __patch_func__ = patch
    __unpatch_func__ = unpatch
    __get_version__ = get_version

    def _assert_sync_wrapped(self, assert_method, pymongo):
        """Assert sync methods are wrapped/unwrapped."""
        assert_method(pymongo.MongoClient.__init__)
        assert_method(Topology.select_server)

        if _VERSION >= (3, 12):
            assert_method(Server.run_operation)
        elif _VERSION >= (3, 9):
            assert_method(Server.run_operation_with_response)
        else:
            assert_method(Server.send_message_with_response)

        if _VERSION >= (4, 5):
            assert_method(Server.checkout)
        else:
            assert_method(Server.get_socket)

        assert_method(Connection.command)
        assert_method(Connection.write_command)

    def _assert_async_wrapped(self, assert_method):
        """Assert async methods are wrapped/unwrapped (pymongo >= 4.12 only)."""
        if _VERSION >= (4, 12):
            assert_method(AsyncMongoClient.__init__)  # type: ignore[name-defined]
            assert_method(AsyncTopology.select_server)  # type: ignore[name-defined]
            assert_method(AsyncServer.run_operation)  # type: ignore[name-defined]
            assert_method(AsyncServer.checkout)  # type: ignore[name-defined]
            assert_method(AsyncConnection.command)  # type: ignore[name-defined]
            assert_method(AsyncConnection.write_command)  # type: ignore[name-defined]

    def assert_module_patched(self, pymongo):
        self._assert_sync_wrapped(self.assert_wrapped, pymongo)
        self._assert_async_wrapped(self.assert_wrapped)

    def assert_not_module_patched(self, pymongo):
        self._assert_sync_wrapped(self.assert_not_wrapped, pymongo)
        self._assert_async_wrapped(self.assert_not_wrapped)

    def assert_not_module_double_patched(self, pymongo):
        self.assert_not_double_wrapped(pymongo.MongoClient.__init__)
        self.assert_not_double_wrapped(Topology.select_server)
        self.assert_not_double_wrapped(Connection.command)
        self.assert_not_double_wrapped(Connection.write_command)

        if _VERSION >= (3, 12):
            self.assert_not_double_wrapped(Server.run_operation)
        elif _VERSION >= (3, 9):
            self.assert_not_double_wrapped(Server.run_operation_with_response)
        else:
            self.assert_not_double_wrapped(Server.send_message_with_response)

        if _VERSION >= (4, 5):
            self.assert_not_double_wrapped(Server.checkout)
        else:
            self.assert_not_double_wrapped(Server.get_socket)

        self._assert_async_wrapped(self.assert_not_double_wrapped)
