from typing import List

class PyConfigurator:
    def __init__(self, debug_logs: bool): ...
    def set_envp(self, envp: List[str]) -> None: ...
    def set_args(self, args: List[str]) -> None: ...
    def get_configuration(self) -> dict: ...
