from ddtrace.vendor import wrapt
from typing import Any

log: Any

class WrappedClient(wrapt.ObjectProxy):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set(self, *args: Any, **kwargs: Any): ...
    def set_many(self, *args: Any, **kwargs: Any): ...
    def add(self, *args: Any, **kwargs: Any): ...
    def replace(self, *args: Any, **kwargs: Any): ...
    def append(self, *args: Any, **kwargs: Any): ...
    def prepend(self, *args: Any, **kwargs: Any): ...
    def cas(self, *args: Any, **kwargs: Any): ...
    def get(self, *args: Any, **kwargs: Any): ...
    def get_many(self, *args: Any, **kwargs: Any): ...
    def gets(self, *args: Any, **kwargs: Any): ...
    def gets_many(self, *args: Any, **kwargs: Any): ...
    def delete(self, *args: Any, **kwargs: Any): ...
    def delete_many(self, *args: Any, **kwargs: Any): ...
    def incr(self, *args: Any, **kwargs: Any): ...
    def decr(self, *args: Any, **kwargs: Any): ...
    def touch(self, *args: Any, **kwargs: Any): ...
    def stats(self, *args: Any, **kwargs: Any): ...
    def version(self, *args: Any, **kwargs: Any): ...
    def flush_all(self, *args: Any, **kwargs: Any): ...
    def quit(self, *args: Any, **kwargs: Any): ...
    def set_multi(self, *args: Any, **kwargs: Any): ...
    def get_multi(self, *args: Any, **kwargs: Any): ...
