import asyncio
from types import FrameType
from typing import Optional
from typing import Sequence
from typing import Union

from ddtrace._trace import context
from ddtrace._trace import span as ddspan

# Core stack v2 functions
def start(min_interval: float = ...) -> bool: ...
def stop() -> None: ...

# Sampling configuration
def set_adaptive_sampling(do_adaptive_sampling: bool = False) -> None: ...
def set_interval(new_interval: float) -> None: ...

# span <-> profile association
def link_span(span: Optional[Union[context.Context, ddspan.Span]]) -> None: ...

# Thread management
def register_thread(python_thread_id: int, native_id: int, name: str) -> None: ...
def unregister_thread(python_thread_id: int) -> None: ...

# Asyncio support
def track_asyncio_loop(thread_id: int, loop: Optional[asyncio.AbstractEventLoop]) -> None: ...
def link_tasks(parent: asyncio.Task, child: asyncio.Future) -> None: ...
def init_asyncio(
    current_tasks: Sequence[asyncio.Task],
    scheduled_tasks: Sequence[asyncio.Task],
    eager_tasks: Optional[Sequence[asyncio.Task]],
) -> None: ...

# Greenlet support
def track_greenlet(greenlet_id: int, name: str, frame: Union[FrameType, bool, None]) -> None: ...
def untrack_greenlet(greenlet_id: int) -> None: ...
def link_greenlets(greenlet_id: int, parent_id: int) -> None: ...
def update_greenlet_frame(greenlet_id: int, frame: Union[FrameType, bool, None]) -> None: ...

# Module attributes
is_available: bool
failure_msg: str
