"""Type stubs for the native `_stack` C extension module."""

import asyncio
from types import FrameType
from typing import Any
from typing import Optional
from typing import Sequence
from typing import Union

# Core stack v2 functions
def start(min_interval: float = ...) -> bool: ...
def stop() -> None: ...

# Sampling configuration
def set_adaptive_sampling(do_adaptive_sampling: bool = False) -> None: ...
def set_target_overhead(target_overhead: float) -> None: ...
def set_max_sampling_period(max_interval_us: int) -> None: ...
def set_max_threads(max_threads: int) -> None: ...
def set_uvloop_mode(thread_id: int, uvloop_mode: bool) -> None: ...
def set_interval(new_interval: float) -> None: ...

# Memory copy strategy
def set_fast_copy(enabled: bool) -> None: ...
def is_safe_copy_failed() -> bool: ...

# span <-> profile association
def link_span(
    span_id: int,
    local_root_span_id: int,
    span_type: Optional[str] = None,
) -> None: ...

# Thread management
def register_thread(python_thread_id: int, native_id: int, name: str) -> None: ...
def unregister_thread(python_thread_id: int) -> None: ...

# Asyncio support
def track_asyncio_loop(thread_id: int, loop: Optional[asyncio.AbstractEventLoop]) -> None: ...
def link_tasks(parent: asyncio.Task[Any], child: asyncio.Future[Any]) -> None: ...
def weak_link_tasks(parent: asyncio.Task[Any], child: asyncio.Future[Any]) -> None: ...
def init_asyncio(
    scheduled_tasks: Sequence[asyncio.Task[Any]],
    eager_tasks: Optional[Sequence[asyncio.Task[Any]]],
) -> None: ...

# Greenlet support
def track_greenlet(greenlet_id: int, name: str, frame: Union[FrameType, bool, None]) -> None: ...
def untrack_greenlet(greenlet_id: int) -> None: ...
def link_greenlets(greenlet_id: int, parent_id: int) -> None: ...
def update_greenlet_frame(greenlet_id: int, frame: Union[FrameType, bool, None]) -> None: ...

# Native call monitoring (sys.monitoring bridge)
def start_native_monitoring() -> None: ...
def stop_native_monitoring() -> None: ...
