# This test script was automatically generated by the contrib-patch-tests.py
# script. If you want to make changes to it, you should make sure that you have
# removed the ``_generated`` suffix from the file name, to prevent the content
# from being overwritten by future re-generations.

from ddtrace.contrib.kafka.patch import patch


try:
    from ddtrace.contrib.kafka.patch import unpatch
except ImportError:
    unpatch = None
from tests.contrib.patch import PatchTestCase


class TestKafkaPatch(PatchTestCase.Base):
    __integration_name__ = "kafka"
    __module_name__ = "confluent_kafka"
    __patch_func__ = patch
    __unpatch_func__ = unpatch

    def assert_module_patched(self, confluent_kafka):
        self.assert_wrapped(confluent_kafka.Producer)
        self.assert_wrapped(confluent_kafka.Consumer)

    def assert_not_module_patched(self, confluent_kafka):
        self.assert_not_wrapped(confluent_kafka.Producer)
        self.assert_not_wrapped(confluent_kafka.Consumer)

    def assert_not_module_double_patched(self, confluent_kafka):
        self.assert_not_double_wrapped(confluent_kafka.Producer)
        self.assert_not_double_wrapped(confluent_kafka.Consumer)
