HIGHER_ORDER_TRACE_ID_BITS = "_dd.p.tid"
SAMPLING_DECISION_TRACE_TAG_KEY = "_dd.p.dm"
LAST_DD_PARENT_ID_KEY = "_dd.parent_id"
DEFAULT_SERVICE_NAME = "unnamed-python-service"
SAMPLING_DECISION_MAKER_INHERITED = "_dd.dm.inherited"
SAMPLING_DECISION_MAKER_SERVICE = "_dd.dm.service"
SAMPLING_DECISION_MAKER_RESOURCE = "_dd.dm.resource"
SPAN_LINK_KIND = "dd.kind"
SPAN_LINKS_KEY = "_dd.span_links"
PROCESS_TAGS = "_dd.tags.process"
PROPAGATED_HASH = "_dd.propagated_hash"
_SERVICE_SOURCE = "_dd.svc_src"
SPAN_EVENTS_HAS_EXCEPTION = "_dd.span_events.has_exception"

MESSAGING_BATCH_COUNT = "messaging.batch_count"
MESSAGING_DESTINATION_NAME = "messaging.destination.name"
MESSAGING_MESSAGE_ID = "messaging.message_id"
MESSAGING_OPERATION = "messaging.operation"
MESSAGING_SYSTEM = "messaging.system"

