from typing import Any, Optional

log: Any
ASGI_VERSION: str
ASGI_SPEC_VERSION: str

def bytes_to_str(str_or_bytes: Any): ...

class TraceMiddleware:
    app: Any = ...
    tracer: Any = ...
    integration_config: Any = ...
    handle_exception_span: Any = ...
    span_modifier: Any = ...
    def __init__(self, app: Any, tracer: Optional[Any] = ..., integration_config: Any = ..., handle_exception_span: Any = ..., span_modifier: Optional[Any] = ...) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any): ...
