from typing import Any

def patch() -> None: ...
def unpatch() -> None: ...
def traced_execute_command(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_pipeline(func: Any, instance: Any, args: Any, kwargs: Any): ...
def traced_execute_pipeline(func: Any, instance: Any, args: Any, kwargs: Any): ...
