"""
The ``gc`` integration adds spans generated by the python GC in Py3.3+

https://docs.python.org/3/library/gc.html#gc.callbacks
"""
import sys

if sys.version_info[0] >= 3 and sys.version_info[1] >= 3:
    from .patch import patch, unpatch

    __all__ = [
        'patch',
        'unpatch'
    ]
