import Any
from psycopg2.extensions import connection, cursor
from typing import Optional

def connection_factory(tracer: Any, service: Any=...) -> Any: ...

class TracedCursor(cursor):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def execute(self, query: Any, vars: Optional[Any] = ...): ...
    def callproc(self, procname: Any, vars: Optional[Any] = ...): ...

class TracedConnection(connection):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cursor(self, *args: Any, **kwargs: Any): ...
