name: Hook style
on:
  push:
    branches:
      - main
      - mq-working-branch-*
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  shellcheck:
    name: shellcheck hook scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install hatch
        run: pip install hatch

      - name: Run shellcheck
        run: hatch run lint:hook-style
