"""Tests for ``scripts/check_lockfile_cooldown.py``.

The validator is the defense-in-depth half of TEST-CD (APMLP-1362). These
tests cover the bits of the script that don't need network access:
the lockfile parser and the cooldown decision logic. Network calls are
patched out so the suite stays hermetic.
"""

import datetime as dt
import importlib.util
import pathlib
import sys
import textwrap
from unittest import mock

import pytest


_SCRIPT_PATH = pathlib.Path(__file__).resolve().parents[2] / "scripts" / "check_lockfile_cooldown.py"


@pytest.fixture(scope="module")
def cooldown_mod():
    """Import ``scripts/check_lockfile_cooldown.py`` as a module."""
    spec = importlib.util.spec_from_file_location("check_lockfile_cooldown", _SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(tmp_path: pathlib.Path, content: str) -> pathlib.Path:
    lockfile = tmp_path / "lockfile.txt"
    lockfile.write_text(textwrap.dedent(content).lstrip("\n"))
    return lockfile


def test_parse_lockfile_skips_comments_options_and_dashes(cooldown_mod, tmp_path):
    lockfile = _write(
        tmp_path,
        """
        # autogenerated header
        # by pip-compile
        -e .
        [option]
        attrs==26.1.0
        flask[async]==3.0.0  # inline comment
        # blank line below

        PyYAML==6.0.1
        """,
    )

    assert cooldown_mod._parse_lockfile(lockfile) == [
        ("attrs", "26.1.0"),
        ("flask", "3.0.0"),
        ("pyyaml", "6.0.1"),
    ]


def test_parse_lockfile_skips_pypi_excluded(cooldown_mod, tmp_path):
    """pip / setuptools / wheel are tracked by the base-image layer instead."""
    lockfile = _write(
        tmp_path,
        """
        pip==25.0
        setuptools==80.0.0
        wheel==0.45.0
        requests==2.32.4
        """,
    )

    assert cooldown_mod._parse_lockfile(lockfile) == [("requests", "2.32.4")]


def test_parse_pypi_upload_time_handles_both_formats(cooldown_mod):
    parse = cooldown_mod._parse_pypi_upload_time
    with_micro = parse("2026-05-20T10:00:00.000000Z")
    without_micro = parse("2026-05-20T10:00:00Z")
    assert with_micro == without_micro
    assert with_micro is not None
    assert with_micro.tzinfo == dt.timezone.utc
    assert parse("not-a-timestamp") is None


def test_collect_pins_deduplicates_across_lockfiles(cooldown_mod, tmp_path):
    a = _write(tmp_path, "attrs==26.1.0\nflask==3.0.0\n")
    b = tmp_path / "b.txt"
    b.write_text("attrs==26.1.0\nrequests==2.32.4\n")

    pins = cooldown_mod._collect_pins([a, b])
    assert set(pins.keys()) == {("attrs", "26.1.0"), ("flask", "3.0.0"), ("requests", "2.32.4")}
    # attrs appears in both lockfiles, but we only have one entry.
    assert sorted(p.name for p in pins[("attrs", "26.1.0")]) == ["b.txt", "lockfile.txt"]


def test_check_pin_flags_too_fresh(cooldown_mod):
    now = dt.datetime(2026, 5, 20, 10, 0, 0, tzinfo=dt.timezone.utc)
    uploaded = now - dt.timedelta(hours=12)
    cooldown = dt.timedelta(days=2)

    with mock.patch.object(cooldown_mod, "_release_upload_time", return_value=uploaded):
        violation = cooldown_mod._check_pin("pwn", "1.2.3", now, cooldown)

    assert violation is not None
    name, version, age = violation
    assert (name, version) == ("pwn", "1.2.3")
    assert age == dt.timedelta(hours=12)


def test_check_pin_allows_old_enough(cooldown_mod):
    now = dt.datetime(2026, 5, 20, 10, 0, 0, tzinfo=dt.timezone.utc)
    uploaded = now - dt.timedelta(days=10)
    cooldown = dt.timedelta(days=2)

    with mock.patch.object(cooldown_mod, "_release_upload_time", return_value=uploaded):
        assert cooldown_mod._check_pin("safe", "1.0.0", now, cooldown) is None


def test_check_pin_skips_when_upload_time_unknown(cooldown_mod, capsys):
    now = dt.datetime(2026, 5, 20, 10, 0, 0, tzinfo=dt.timezone.utc)
    cooldown = dt.timedelta(days=2)

    with mock.patch.object(cooldown_mod, "_release_upload_time", return_value=None):
        assert cooldown_mod._check_pin("private", "9.9.9", now, cooldown) is None

    captured = capsys.readouterr()
    assert "private==9.9.9" in captured.err


def test_main_fails_when_pin_is_too_fresh(cooldown_mod, tmp_path):
    lockfile = _write(tmp_path, "attrs==26.1.0\n")

    now = dt.datetime.now(dt.timezone.utc)

    def fake_upload_time(name, version):
        return now - dt.timedelta(hours=1)

    with mock.patch.object(cooldown_mod, "_release_upload_time", side_effect=fake_upload_time):
        rc = cooldown_mod.main([str(lockfile), "--cooldown-days", "2"])

    assert rc == 1


def test_main_passes_when_all_pins_are_old(cooldown_mod, tmp_path):
    lockfile = _write(tmp_path, "attrs==26.1.0\nflask==3.0.0\n")

    now = dt.datetime.now(dt.timezone.utc)

    def fake_upload_time(name, version):
        return now - dt.timedelta(days=30)

    with mock.patch.object(cooldown_mod, "_release_upload_time", side_effect=fake_upload_time):
        rc = cooldown_mod.main([str(lockfile), "--cooldown-days", "2"])

    assert rc == 0
